### ISSUE TITLE
ods-deployments file repeats image in mono repository setup

### ISSUE THREAD

**Issue by albertpuente** [opendevstack/ods-jenkins-shared-library#1011]
**Describe the bug**
When using a single component with multiple images being built with `odsComponentStageBuildOpenShiftImage()` and deployed via Helm, the ods-deployments file does not properly reflect the names and hashes of the different images.

**To Reproduce**
1. Create a component with multiple images being built.
2. Use helm as the tool to deploy such component by adding a chart.
3. Deploy the comoponent to dev.

**Expected behavior**
The ods-deployments.json file of the component should contain different images instead of repeating the first image.

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
See excerpts below:
```json
{
    "deployments": {
        "pid-backend": {
            "containers": {
                "backend": "pid-backend@sha256:786b248f3e783777f1ea6eb2243cba975ff28ed8ee7fd0fc7f951a463fbde242"
            },
            "deploymentMean": {
                "type": "helm",
                ...
            }
        },
        "pid-frontend": {
            "containers": {
                "backend": "pid-backend@sha256:786b248f3e783777f1ea6eb2243cba975ff28ed8ee7fd0fc7f951a463fbde242"
            },
            "deploymentMean": {
                "type": "helm",
                ...
            }
        },
        "pid-cache": {
            "containers": {
                "backend": "pid-backend@sha256:786b248f3e783777f1ea6eb2243cba975ff28ed8ee7fd0fc7f951a463fbde242"
            },
            "deploymentMean": {
                "type": "helm",
                ...
            }
        }
    },
    "CREATED_BY_BUILD": "0.1.2/1324"
}
```

**Affected version (please complete the following information):**
 - OpenShift: 3.12
 - OpenDevStack 4.x

**Additional context**
This problem was reported by @gerardcl.

**Comment by metmajer** [comment]
Hi @serverhorror, looks like we have a bug. Can you look into this?

**Comment by metmajer** [comment]
@serverhorror we have enough topics to work on. Let's hope that not too many bugs come up from your integration. Overall, ownership is still on you.
