### ISSUE TITLE
Skip shared lib build / deploy if commits did not change

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#103]
During testing of the MRO lib - we figured out that the shared lib will rebuild the component even if neither the shared lib commit or the component commit changed. 

This should be changed, if nothing changed, just return, and don't build

@metmajer  fyi

**Comment by michaelsauter** [comment]
As I see it there are two options:

1. Compare with previous Jenkins build
2. Compare with latest image in OpenShift

(2) assumes that we are actually building an image in OpenShift, which me might not do ...

As a side note, this might also be helpful for scenarios where we have multiple pipelines within one repository. This is possible since a few weeks (by adding more webhooks to a repo, and adjusting the component name of each). In that case, we probably only want to build each pipeline if the folder in which the pipeline is has changed compared to the previous commit.

**Comment by michaelsauter** [comment]
@clemensutschig Regarding the target: I would take this off from 1.2.0, and put it into the next release ...

**Comment by michaelsauter** [comment]
Taking this out of ODS 2 ... let's consider again when we prioritise for ODS 3.

**Comment by clemensutschig** [comment]
ok - we try to take this up for ods3 ... now with all pieces in one place . this is much easier ..

Proposal:
1. Tag every built image with the commit sha as well
1. In the Build stage (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/BuildOpenShiftImageStage.groovy) - check if tag for commit exists, via tag and then label check if the commits do *really* match
1. If it does - tag it to the current build, and move on ... 
1. If that image is currently deployed - skip deploy, if not, deploy
1. fill ODS / MRO needed data :)

**Comment by clemensutschig** [comment]
OMG .. @metmajer  - you gave me the enlighting thought ...

in the MRO - we can check *before* - if the image is available and deployed - in case it is - the image contains (thanks ods) - the build id from jenkins that deployed it - which would allow us to find the right docs on nexus - for TIR and DTR ... and voila, we would not even need to start the *component* pipeline ... 

@michaelsauter  thoughts?

**Comment by michaelsauter** [comment]
Makes we wonder ... if you "build the same commit again" - aren't we actually building a new SHA? Say we run the orchestration pipeline for the first time, we build SHA `abc`, then there's an image which points to commit `abc`. However, in the finalize stage, we create a new commit, `def`. Next time we run the orchestration pipeline, Jenkins will look at `def`, so the SHA is not the same as the one recorded in the image ... right?

Maybe we should link the commit that is created in the finalize stage to the build commit ... basically: if the orchestration pipeline finds HEAD to be a commit that the orchestration pipeline itself created in a previous pipeline, then one can check the commit that was built originally.

**Comment by clemensutschig** [comment]
I have a first prototype Running..  which takes the latest committed `deployments.json` as master with all Sorry of checks.. the next piece is the docs..  here i need to play with an approach ...

**Comment by clemensutschig** [comment]
ok - this will ONLY work for Dev .. w/o changing @michaelsauter 's implementation too much - we only commt the state of dev - so I don't have any place to store a Q build identifier ... which imho is not a big deal, because on dev - you want to try over and over again
