### ISSUE TITLE
Shared lib clone environment always stores @master in oc-config-artifacts

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#105]
The Shared lib with Source env cloning turned on always stores the artifacts on the master brauch.. this is not good.. especially in the mro context.

Ill take this up in #101 additional changes

@michaelsauter cool?

**Comment by clemensutschig** [comment]
I suggest to use the build number, job name and source environment to keep tracibility.

**Comment by michaelsauter** [comment]
Yes, sounds like a good idea.

However, in general, I am not sure if we want to use env cloning together with the MRO pipeline? I haven't thought about it and am not sure whether it is "compatible" :)

Also, we need to figure out (separately) how the work in #85 affects env cloning long-term

**Comment by clemensutschig** [comment]
We need env cloning ;-)
That way One can Test a füll App build from scratch..  i will try this Next week.. ;-)
