### ISSUE TITLE
add subprojects scanning to snyk scan stage

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-jenkins-shared-library#115]

**Comment by gerardcl** [comment]
Hi @stitakis , can you add a short description for this issue, please? like why it is required? thanks!

**Comment by stitakis** [comment]
This is required to enable skyn cli to scan project with subprojects (modules). I.e gradle or maven support projects structured with one parent project and many sub-project (modules).

**Comment by stitakis** [comment]
As ref: https://snyk.io/docs/cli-test/

**Comment by gerardcl** [comment]
thanks!
