### ISSUE TITLE
CopyImageStage: skopeo --preserve-digests

### ISSUE THREAD

**Issue by dechants** [opendevstack/ods-jenkins-shared-library#1166]
**Is your feature request related to a problem? Please describe.**
We copy images from a private registry hosted by one of our vendors to our internal registries. Their deployment code checks image digests.

**Describe the solution you'd like**
Could you please add skopeo's `--preserve-digests` option?

**Describe alternatives you've considered**
Disabling digest checks during deployment. However, this is a validated application and digests are documented.

**Comment by tbugfinder** [comment]
Hello @dechants,

that really makes sense! Do you think this option should be configurable or a hardcoded default should be ok?


Thanks

**Comment by tbugfinder** [comment]
Ref

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/CopyImageStage.groovy#L89-#L93

**Comment by dechants** [comment]
Hi @tbugfinder 

in our case hardcoded will do, but it is a skopeo option so it probably should be an option for this component as well. I have no clue if other teams have use cases that require new digests.

**Comment by tbugfinder** [comment]
I've create PR #1171.
After running few tests the overall digest is only preserved if `--all` is combined with `--preserve-digests`.
