### ISSUE TITLE
use devcontainer for development

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-jenkins-shared-library#1172]
**Is your feature request related to a problem? Please describe.**
A development cycle for this repository requires specific toolset and versions in place.
It is cumbersome to download and install those while using an isolate devlopment environment.

**Describe the solution you'd like**
Using a devcontainer would be very beneficial for smaller updates and lowers the bar for getting started.

```devcontainer/.devcontainer.json
{
  "image": "gradle:jdk11-focal",
  "containerEnv": {
  },
  "features": {
    "ghcr.io/devcontainers/features/go:1": {"version": "1.15"}
  }
}

```

**Describe alternatives you've considered**
No contribution :-D 

**Additional context**
N/A

**Comment by mobilutz** [comment]
I was just testing it out with devcontainer, and it is working.

It still took a bit to find out how to setup things, but with running this inside the devcontainer I could build and run the tests:
```sh
cd /workspaces/ods-jenkins-shared-library
NO_NEXUS=true ./gradlew clean build
```

I thinkt it would be very good to have such a setup here in the repo and have it documented how to start and run everything.

**Comment by tbugfinder** [comment]
Env NO_NEXUS can be added easily.
Have you installed any other tool?
I'll tidy the PR a bit, then.
