### ISSUE TITLE
Jenkins Slave spin-up fails, if memory quota is enabled

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-jenkins-shared-library#118]
if memory quota is set for the -cd project, jenkins master cannot spin up slaves.

Jenkins master correctly specifies memory limits

https://github.com/opendevstack/ods-project-quickstarters/blob/816fd3f8f849c0b344e858675cf0ca22a12b3e86/ocp-templates/ocp-config/cd-jenkins-master/cd-jenkins-master.yml#L177 and following lines

but seems that nothing is done regarding the slaves.

**Comment by rattermeyer** [comment]
A possible solution could be to introduce overridable config entries:

and uses these to configure the podTemplate / containerTemplate as described here:
https://github.com/jenkinsci/kubernetes-plugin#container-configuration

We would need to modify the containerTemplate in the context:
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsContext.groovy#L112 ff

**Comment by henrjk** [comment]
Yes, I agree that this is needed, not sure it is a bug. 

As a work around I believe one can also define the pod template for the slave in the Jenkinsfile. 
Being able to easily customize slave quotas and get sensible defaults makes sense to me.

**Comment by rattermeyer** [comment]
Think it is a bug, because we have *some* definitions in place for memory quotas, but it is simply not working. On the other hand no one has ever asserted, that it should be working ...
I will test the above solution

**Comment by michaelsauter** [comment]
Doesn't #113 solve that?

**Comment by rattermeyer** [comment]
Yes, it would. haven't see this. have it implemented as additional configurable properties

**Comment by michaelsauter** [comment]
Closing this as the issue itself is solved. I filed a new enhancement to make configuration easy: #173.
