### ISSUE TITLE
Getting last successful commit breaks the build

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#137]
**Describe the bug**
This line `config.lastSuccessfulCommit = retrieveLastSuccessfulCommit()` in `assemble()` issues the following:
```
curl -g --fail --silent 'https://jenkins-foo-cd.lastSuccessfulBuildlastSuccessfulBuildad.bi-x.openshiftapps.com/job/foo-cd/job/foo-cd-be-bar-release-qux/lastSuccessfulBuild/api/json/?tree=actions[lastBuiltRevision[SHA1]]'
```
... and results in an error:
```
ERROR: script returned exit code 6
```

**To Reproduce**
Run a Jenkins build using latest master.

**Expected behavior**
No error should be triggered - further, if an error happens, it should not break the build. Also, I don't think we should fill this information for every build, as most users will not need it.

**Affected version (please complete the following information):**
 - OpenShift: all
 - OpenDevStack: 1.2.0

**Comment by gerardcl** [comment]
this https://github.com/opendevstack/ods-jenkins-shared-library/commit/d8a60093351552d8ab60df2c411fcbb840886c7d closes #137
this error  got promoted, feature is not ready yet --> will come later in the future once fully working
