### ISSUE TITLE
shared library should allow to stay on master node rather than spawning a slave pod

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#145]
in case no slave is needed, but one wants to use the shared lib features, we should offer a way to stay on node: master

**Comment by michaelsauter** [comment]
Not sure this is possible because some of the shared lib features currently depend on the base slave image: e.g. SonarQube scan + report and Snyk scan.

Is the main motivation here speed? If so, maybe we can find other ways to improve that. I am concerned that if we support too many "working styles", then the (im)possible combination of features can get really complicated in the long run and things are more likely to break ...

**Comment by clemensutschig** [comment]
@michaelsauter  - fair enough ... I am just working on integrating functional testing (which is a set of rest calls that are orchestrated ... ) and here the slave is overhead (no image etc created, no "custom" code)... but still want to use the MRO magic, and hence the ods-jenkins ... lib :)

thoughts?

**Comment by michaelsauter** [comment]
So you don't use any stages that need binaries from the slave?

I am afraid that if we allow this, we "lock" ourselves in - going forward we can't provide any functionality in the shared-lib/MRO that requires some dependency, without installing that dependency in slave AND master. So over time all dependencies end up in Jenkins master, which already is a beast. 

Another consideration is e.g. memory usage. If you run on the master, you share that pods resources - you are not under that constraint on the slave.

So I am really not that convinced (yet) that we want to go down that route :)

I think for your use case, one big improvement would be if you get a stable slave pod that is immediately there. This will also help others, so I think we should make this easier to achieve.

**Comment by michaelsauter** [comment]
Alright, let's pursue the improvement of the pod retention than, which is already tracked in #125.

I'll go ahead and close this one. Feel free to re-open though if you think that we should continue to think about this.
