### ISSUE TITLE
Snyk scan stage report generation 

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-jenkins-shared-library#148]
Problem Description:
Currently no report is generated as result of the execution of the snyk stage. In order to review the results a developer needs to find the scan results in the log file. This makes difficult to review the snyk scan result. 

Proposed Solution:
A snyk scan report needs to be generated in order to enable quick review and documentation of the snyk scan results. This can be easily done by appending the snyk cli command output to a file.

**Comment by stitakis** [comment]
@clemensutschig would the generation of snyk scan report enable mro pipeline to verify if snyk scan stage ran and additionally add the report to the documentation? (@maksymmaksym fyi)

**Comment by clemensutschig** [comment]
Here is my Proposal. Similar to sqscan stage attach it to the run. Ja there a way to break the stage based on findings?

**Comment by stitakis** [comment]
@clemensutschig I'll use the same pattern for report generation. For Sonarqube the keyword "SCRR" is being used. For synk I would use something like "SCSR" (Scan Snyk Report), is this ok? Or should I follow a different naming pattern? In that case, which one?

**Comment by stitakis** [comment]
@clemensutschig I have create a draft PR so you can review it... implementation uses same pattern that you proposed above
