### ISSUE TITLE
Investigate automated testing for shared library

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#149]
See discussion in #146.

From https://github.com/opendevstack/ods-jenkins-shared-library/issues/146#issuecomment-546284767:

> Hm, for experimenting locally with Jenkinsfiles I often use https://github.com/jenkinsci/jenkinsfile-runner since @ungerts recommended it to me a few months ago.

From https://github.com/opendevstack/ods-jenkins-shared-library/issues/146#issuecomment-546314483:

> On my agenda is also to take a look at https://github.com/jenkinsci/JenkinsPipelineUnit

**Comment by michaelsauter** [comment]
@oalyman Can you add your findings to this ticket as well?

**Comment by oalyman** [comment]
As the ods-jenkins-shared-library uses the [jenkins-client-plugin](https://github.com/openshift/jenkins-client-plugin) I had a look into how this is tested.

They are doing a full-blown integration test by building a Jenkins image with a snapshot of their changes and then running the extended tests from origin e.g. [pipeline_jenkins_e2e.go](https://github.com/openshift/origin/blob/6ae0a501b493302e7f4fb8e84c06b104007d9e62/test/extended/builds/pipeline_jenkins_e2e.go)

Reference Link [PR-Testing ods-jenkins-shared-library](https://github.com/openshift/jenkins-client-plugin/tree/master/PR-Testing).

**Comment by metmajer** [comment]
Worth noting that there seemed to be some consensus on using Spock for unit testing in #146, so this shouldn't go unmentioned.

**Comment by metmajer** [comment]
@hugowschneider I invite you to a tour through how we automatically test the MRO Jenkins shared library that powers the Release Manager. Meanwhile > 7500 autoamted tests ;-)

**Comment by renedupont** [comment]
I picked that up again and integrated https://github.com/jenkinsci/JenkinsPipelineUnit next to Spock to the shared lib in this merged PR #202 
If no one objects, I'd see that issue as completed as we now have Spock and this JenkinsPipelineUnit integrated in the shared lib. 
There are still many tests to write, but I guess that is another story.

**Comment by michaelsauter** [comment]
I see this as closed. @renedupont put the framework in place, and I am doing further refactoring and adding tests along the way.
