### ISSUE TITLE
docs: how to request resources for Jenkins slave pods?

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-jenkins-shared-library#150]
I want to request more resources (CPU, Memory, Ephemeral Storage) for my own Custom Jenkins Slave. As I could not find anything in the documentation, how can I do that?

**Comment by michaelsauter** [comment]
Please see https://www.opendevstack.org/ods-documentation/ods-jenkins-shared-library/latest/index.html#_slave_customization.

Also check how the default is implemented: https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsContext.groovy#L119-L131.

**Comment by SimonGolms** [comment]
Unfortunately, there are no examples available and it is quite time consuming to find out the appropriate code snippets in the source code and debug whatever is possible. Also which is the recommendation for it, because it seems that you can do it via `Jenkinsfile` and the `kubernetes plugin`. Please pay attention to this when you write the documentation!

Anyway, for everyone else who stumbles over the issue, here is an code example of my current succesfull running `Jenkinsfile`.

```groovy
odsPipeline(
  projectId: projectId,
    podContainers: [
      containerTemplate(
        name: 'jnlp', // do not change
        image: "${dockerRegistry}/cd/jenkins-slave-nodejs10-angular",
        workingDir: '/tmp',
        resourceRequestMemory: '1Gi',
        resourceLimitMemory: '4Gi',
        alwaysPullImage: true,
        args: '${computer.jnlpmac} ${computer.name}'
      )
  ],
  componentId: componentId,
  branchToEnvironmentMapping: [
    'master': 'test',
    'dev': 'dev',
  ],
  debug: true
  ) { context ->
  stageBuild(context)
  stageUnitTest(context)
  //stageScanForSonarqube(context)
  stageStartOpenshiftBuild(context)
  stageDeployToOpenshift(context)
}

```

**Comment by michaelsauter** [comment]
@SimonGolms OK! Thanks for the example. Could you please contribute that to the documentation? I think you need to make your changes in https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/docs/modules/ROOT/pages/index.adoc.

**Comment by SimonGolms** [comment]
see #152
