### ISSUE TITLE
Get last successful build

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-jenkins-shared-library#155]
Retrieving the last successful build is useful to see what files are successfully committed to the repository. This issue is also related to and a prerequisite to what's specified [#92 ](https://github.com/opendevstack/ods-jenkins-shared-library/issues/92).
So far there are two ways to retrieve this information that I've ran across:
- Taking advantage of Jenkins shared library being a global library and being freely able to use library methods (without requiring script approval by any admin like user)
- Making a curl request with user credentials to Jenkins (not sure which user to use here)

**Comment by clemensutschig** [comment]
@michaelsauter  / @sino92  - as we run in a global shared lib now .. this should be pretty easy?

**Comment by michaelsauter** [comment]
@sino92 I believe you already had a simplified PR of this in Bitbucket, right?

**Comment by sino92** [comment]
@clemensutschig it's quite easy and yes @michaelsauter I had a pending PR in BB. Please take a look at your convenience.
