### ISSUE TITLE
tedious to test and make changes in auto clone scripts

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-jenkins-shared-library#167]
**Is your feature request related to a problem? Please describe.**
As a developer making changes in the import/export scripts used by the auto clone ods environment feature I need to branch 3 projects and unexpected changes in clone-project.sh:

1. ods-core (to make changes in [clone-project.sh_L95-98](https://github.com/opendevstack/ods-core/blob/0bbb48417085d15515c732fe45185581f74f9c1c/ocp-scripts/clone-project.sh#L95-L98))
2. ods-jenkins-shared-library (to make changes in [OdsPipeline.groovy_L270-280](https://github.com/opendevstack/ods-jenkins-shared-library/blob/b7162281536e4357137995ccae9bf4da5b816bd8/src/org/ods/OdsPipeline.groovy#L270-L280))
3. In a project which tests or use the changes to reference the changed branch of the shared library.

**Describe the solution you'd like**
1. Change the ods-core clone-project.sh script be changed to no longer reference production and instead use the code from its branch.
2. Support passing in a branch to the shared library to be used for referencing the ods-core branch to avoid needing to branch the the shared library.

**Describe alternatives you've considered**
Perhaps there are good reasons for the current design. Then this issue could be used to capture the rationale. 

**Additional context**
NA

**Comment by michaelsauter** [comment]
I think this is a great proposal. We should make the branch configurable.
