### ISSUE TITLE
Print out assembled information only in debug mode

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#171]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsContext.groovy#L168 should only be printed in debug mode

**Comment by renedupont** [comment]
I guess code changed meanwhile? Could you point to the location?

**Comment by michaelsauter** [comment]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsContext.groovy#L206
