### ISSUE TITLE
Ability to set output image tag (at least in parts)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#172]
**Is your feature request related to a problem? Please describe.**
Today the image tag is created from the jenkins build number and commitSha(8) 

ODSContext - l80ff 
```
    config.buildNumber = script.env.BUILD_NUMBER
    ..... 
    config.tagversion = "${config.buildNumber}-${config.gitCommit.take(8)}" 
```

**Describe the solution you'd like**

Be able to set one part of the tag dynamically from outside. 

**Describe alternatives you've considered**
None - need this for MRO

**Comment by clemensutschig** [comment]
@michaelsauter  @metmajer  :D

**Comment by michaelsauter** [comment]
Ok, could you describe what exactly the MRO requirement here is? Maybe there actually is an alternative to changing the image tag directly here. E.g. to apply a second tag to it via the shared library.

**Comment by clemensutschig** [comment]
hey @michaelsauter  - 
when MRO builds - it is in reality only one jenkins build (and not one per component)...

that means the tag that is created per component is *mro jenkins run#*-*sha8*

What would be great is the ability to set the tag- or a prefix ... at runtime thru an environment variable ... when we `call` the component pipeline ..

**Comment by clemensutschig** [comment]
as we have all pieces - e.g. the sha and also the project and component we can tag ourselves ..
<code>
$ oc tag trainods-test/fe-vue@sha256:d66703bd50bb644700ae9060334788b9c7192c3d101106cb5b0e8ba8841fdc96 trainods-test/fe-vue:123

Tag fe-vue:123 set to trainods-test/fe-vue@sha256:d66703bd50bb644700ae9060334788b9c7192c3d101106cb5b0e8ba8841fdc96.
</code>

**Comment by michaelsauter** [comment]
If I get you right, you want the MRO to determine the tag of the images built in the individual pipelines.

For this, I would propose we extend the shared library so that an env variable can be used to set additional tags (next to the one that is created automatically from the git commit being built).

The MRO would then pass the tag name of its choice to the individual pipelines when it calls them.

Did I get it right? Is that what you would like to achieve?

**Comment by clemensutschig** [comment]
mro goes directly against the sha, no need for this
