### ISSUE TITLE
Be able to configure the docker directory to use when building

### ISSUE THREAD

**Issue by oalyman** [opendevstack/ods-jenkins-shared-library#181]
**Is your feature request related to a problem? Please describe.**
Currently the `--from-dir` for `oc start-build` in [stageStartOpenshiftBuild.groovy](https://github.com/opendevstack/ods-jenkins-shared-library/blob/1bd490154235c405bb0d32354ba14a8d25993d37/vars/stageStartOpenshiftBuild.groovy#L13) is fixed to `docker`.
Some build tools already generate a docker directory including a Dockerfile.
Currently, I need to copy stuff over to the `docker` directory.
Additionally, If I choose to use a PV for my build I would need to take care of cleaning up the docker directory again.
Being able to set the docker directory to use one would have more flexibility and might reduce copy/cleanup logic.

**Describe the solution you'd like**
It would be nice if I could configure the directory used for `--from-dir`.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by michaelsauter** [comment]
Agree, might be good not to hardcode. On the other hand, it is kind of nice to have a "ODS way of doing things", so that when I am new to a repo which is deployed using ODS, I know where to look. `docker` folder will be where my `Dockerfile` is.

**Comment by oalyman** [comment]
One doesn't exclude the other.
I just want to copy the static handwritten `Dockerfile` from the `docker` folder to the configured docker folder of my build tool which contains generated files / directories for the docker image.
This way I benefit from automatic cleanup when doing a clean build.
