### ISSUE TITLE
Shared lib shows NO changeset on non master builds

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#19]
a new quickstarter (latest production) - with library identifier: 'ods-library@0.1-latest' - 

with first dummy checkin into a feature branch - shows an empty changelog
(.... job/manu-cd/job/manu-cd-be-node-express-2-dev/16/console)

shows : 

Checking out Revision 0df064bb096657979cc20f3aa71ef94ce0f8c133 (refs/remotes/origin/feature/test-commit)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 0df064bb096657979cc20f3aa71ef94ce0f8c133
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b feature/test-commit 0df064bb096657979cc20f3aa71ef94ce0f8c133
Commit message: "LICENSE edited online with Bitbucket"
First time build. Skipping changelog.
--------------------------------------------------------------------------------------------

Second checkin:

 > git config core.sparsecheckout # timeout=10
 > git checkout -f 4f0e24d5ca6b025d35bea25fab5f3e712e236027
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D feature/test-commit # timeout=10
 > git checkout -b feature/test-commit 4f0e24d5ca6b025d35bea25fab5f3e712e236027
Commit message: "LICENSE edited online with Bitbucket"

First time build. Skipping changelog

--------------------------------
Must fix for 1.0 - and we need to see it flagged (including the environment to publish to with /wfapi/describe ) - which is the json api that also openshift uses :)

in the prepare node 
gitBranch:feature/test-commit, gitCommit:4f0e24d5ca6b025d35bea25fab5f3e712e236027, shortBranchName:test-commit, tagversion:16-4f0e24d5, environment:dev, targetProject:manu-dev

it's available ... drill from
job/manu-cd/job/manu-cd-be-node-express-2-dev/16/wfapi/describe 

to build node:
job/manu-cd/job/manu-cd-be-node-express-2-dev/16/execution/node/16/wfapi/describe

**Comment by michaelsauter** [comment]
Hmm. The shared lib never deals with the changelog directly. The changelog is something that Jenkins does by itself. And from the looks of it, Jenkins does not create a changelog for the first build (which is the case in the dev pipeline, all previous builds were skipped). What would you expect to see? Changes compared to master? If so, I think Jenkins would need us to build the first commit also on the dev pipeline, which is not really what we want :)

The second part of the issue about "flagging" and wfapi, I'm not sure what you mean exactly. Could you give me more background?

**Comment by clemensutschig** [comment]
@Michael- if you build 2 times dev or a Dev like branch you should see a changelog no?

**Comment by michaelsauter** [comment]
@clemensutschig Correct. Definitely if you have two builds for the same branch. Across branches I would have to check if a changelog is shown. However, across branches the changelog wouldn't make much sense ... 

What we are currently trialing in our initiative (one pipeline per branch) would show a changelog only for consecutive builds on the same branch, which makes most sense in my opinion.

**Comment by clemensutschig** [comment]
Ok Please verify if this really Works and then close a Not a Bug ;-)

**Comment by michaelsauter** [comment]
@clemensutschig In the test pipeline, where all builds are for master commits, it definitely works. For dev pipelines, it also shows a changelog if there are multiple builds, but it looks a bit confusing to me. I think the best way is to have one pipeline per branch ...
