### ISSUE TITLE
Unreliable behavior of OdsContext.retrieveGitBranch in an MRO context

### ISSUE THREAD

**Issue by metmajer** [opendevstack/ods-jenkins-shared-library#194]
**Describe the bug**
The current `retrieveGitBranch` implementation sometime returns the wrong branch name, instead of an to-be-expected `master`. I was not able to fully reproduce the issue, but it appears as if a `git merge` from one branch to another, e.g., a fix branch to a feature or master branch, keeps yielding the fix branch.

**Expected behavior**
There should be no need for a rather complex branch lookup in an MRO context, as the Release Manager's metadata.yml supports the configuration of a `branch` property for each component repository. [See here](https://github.com/opendevstack/ods-quickstarters/blob/master/docs/modules/ROOT/pages/release-manager.adoc).

**Affected version (please complete the following information):**
 - OpenDevStack 2

**Proposed solution**
The Release Manager executes a component's pipeline using Jenkins' `load` job. This could be wrapped with a `withEnv` directive that injects the requested branch, as described above through the environment. This effectively reduces the implementation to a 1-liner in `OdsContext.retrieveGitBranch`.

**Comment by clemensutschig** [comment]
@metmajer  at least on master this works, as designed ...  (assuming there is a new commit  on the branch you refer to ... :) .. cool to close?

**Comment by metmajer** [comment]
Yes, we'll reopen if needed.
