### ISSUE TITLE
verbosity of standard shared libary stages

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#196]
**Is your feature request related to a problem? Please describe.**
The ods-jenkins shared lib stages should show a beginning and end echo output that states the component name /and branch

**Describe the solution you'd like**
a standard format (e.g. --- starting stage (...) for component (....) branch (....) and the same thing for finishing)

one more piece. please do NOT alter the stage('...') names ...

**Comment by clemensutschig** [comment]
related to #193

**Comment by renedupont** [comment]
Added withStage groovy method to wrap a stage that echos start and end info of that stage.
See: https://github.com/opendevstack/ods-jenkins-shared-library/pull/202/files#diff-b819e8ce2290d60155c9ca33585f12f6R1
Since it is global, it can be used in Jenkinsfiles directly without any import.
