### ISSUE TITLE
ScanForSonarqube stage should pass author to cnes report creator

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#197]
**Is your feature request related to a problem? Please describe.**
Today - the report generated does not contain and author.. but it should

**Describe the solution you'd like**
The jenkins run and job Name should be passed to the generator to Show up as author..

**Comment by clemensutschig** [comment]
@metmajer fyi

**Comment by clemensutschig** [comment]
@renedupont  - did you do this as well?

**Comment by renedupont** [comment]
Nope, but will look into it.
 
Could you further describe what you mean by 'The jenkins run and job Name'? Especially 'jenkins run' is not clear to me. Could you give an example of the author string that you want to pass?

Maybe one of those?
- Build URL like: http://server:port/jenkins/job/foo/15/
- A build tag like: jenkins-${JOB_NAME}-${BUILD_NUMBER}

Thanks.

**Comment by clemensutschig** [comment]
@renedupont `env.BUILD_TAG`

**Comment by renedupont** [comment]
done in https://github.com/opendevstack/ods-jenkins-shared-library/pull/231
