### ISSUE TITLE
ciSkip check happens on slave node rather than master

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#199]
**Describe the bug**
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsPipeline.groovy#L77

leads to a slave being bootstrapped and then the check happens - this is resource waste

**Expected behavior**
first check after environment, on master, to limit resource consumption

**Affected version (please complete the following information):**
 - OpenDevStack [e.g. 1.0,....]

@renedupont  / @michaelsauter  @metmajer

**Comment by clemensutschig** [comment]
on the same note ... can we put some pattern matching in place on ci skip ... 
what should work is "ciskip", "ci-skip", "ci skip", "ci_skip" and all upperlowercase versions

**Comment by renedupont** [comment]
moved the ciskip higher to avoid resource waste, see
https://github.com/opendevstack/ods-jenkins-shared-library/pull/202/files#diff-9b926a359deb3f339e040516225f076eR51
and added the desired pattern matching:
https://github.com/opendevstack/ods-jenkins-shared-library/pull/202/files#diff-8ea438d8114e00d229e55f0f6bec37c7R11
