### ISSUE TITLE
Add fault tolerance during nexus upload if tar ball already exists

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#2]
If a rebuild without Change is done - say because sth failed after nexus upload a dummy checkin needs to happen otherwise Nexus upload will fail (on purpose) as the tar ball exists- and the developer User has no permissions to overwrite it

**Comment by michaelsauter** [comment]
I think we can close this because we do not upload to Nexus anymore.
