### ISSUE TITLE
Provide stage to generate installation plan & report

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#20]
Configurable

- on which branch / env the task fires
- location where to store the generated pdf(s) with required content - and meta information (xml) (jenkins dc param)

First cut of data needed
- stages including status and time
- commit change history since last build
- target environment
- OC tag created
- OC url 
- Component name

Secondly a copy of the jenkinsFile used for build (including branch / repo and commit)

**Comment by clemensutschig** [comment]
@michaelsauter- as we have to provide docu on build and Installation - the idea is to generate this doc.. Please get in Touch with torsten for more Background

**Comment by michaelsauter** [comment]
Ok, thanks. @torstenhe Could you expand on that? Thanks!

**Comment by michaelsauter** [comment]
I don't see this happening for 1.0. @clemensutschig do you agree? Then we could remove it from the milestone.

**Comment by clemensutschig** [comment]
@michealsauter.. yes agreed

**Comment by gerardcl** [comment]
@clemensutschig moving this to 2.0

**Comment by clemensutschig** [comment]
this is done as part of 1.2 :)
