### ISSUE TITLE
getTestResults() return a boolean value

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-jenkins-shared-library#208]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/818015be9fafda6bd6d123442a300c85ce856fc6/src/org/ods/Context.groovy#L11

I guess this should return a `String`

**Comment by stitakis** [comment]
@clemensutschig @renedupont @gerardcl @metmajer I found this in shared-lib 2.x. in 'Context.groovy`

**Comment by clemensutschig** [comment]
Yup correct..

**Comment by clemensutschig** [comment]
@stitakis .. did you get an error when using testlocation property for Test results?

**Comment by renedupont** [comment]
done in #210
