### ISSUE TITLE
MRO: sonarqube branch should be set to '*' in case of multirepobuild = true

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#213]
**Describe the bug**
as the MRO creates branches dynamically - and relies on a source code review report to generated docs .. the shared lib should set `sonarQubeBranch` to `*` automatically.

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/OdsPipeline.groovy#L133

@metmajer @martsec - fyi. (current workaround .. set to `sonarQubeBranch` to `*` on master before assemble)

**Comment by michaelsauter** [comment]
Is this intended for 2.x or 3.x?

For 3.x, there is a feature which tells the Jenkins master whether multiple branches are supported by the SonarQube edition in use, and based on that modifies the `sonarQubeBranch`.

Maybe we should still force `*` for MRO regardless, but thought I'll mention it here.
