### ISSUE TITLE
startOpenShiftBuild should retry to get the build on 2.x

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#214]
**Describe the bug**
In some cases (Openshift bug?) - although the build is finished (--follow) the build returns still running

![image](https://user-images.githubusercontent.com/40628552/78107325-91e35d00-73f5-11ea-92c4-f9d7e79cf4e9.png)

https://github.com/opendevstack/ods-jenkins-shared-library/blob/2.x/vars/stageStartOpenshiftBuild.groovy#L35

we should retry to get the build a couple times ... to make sure this is mega resilient.

**Comment by michaelsauter** [comment]
This is already fixed :)

https://github.com/opendevstack/ods-jenkins-shared-library/pull/190

**Comment by michaelsauter** [comment]
@clemensutschig Do you want to cherry-pick into 2.x?

**Comment by clemensutschig** [comment]
@michaelsauter  - I fixed it for 2.x slightly different .. but same idea (as the architecture changes)

```
    def buildStatus = ""
    def int retries = 10
    while (buildStatus.toLowerCase() != "complete" && retries > 0)
    {
      sleep 5
      buildStatus = sh(
        returnStdout: true,
        script:"oc -n ${context.targetProject} get build ${buildId} -o jsonpath='{.status.phase}'",
        label: "find last build"
      ).trim()
      retries--
    }
```
