### ISSUE TITLE
Jenkins shared library should support monorepo - multi build / deploy

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#222]
**Is your feature request related to a problem? Please describe.**
Today each repo is bound to a single component - that is set at the root of the shared lib `componentId` - and subsequently used in all stages, thru `context.getComponentId()` . 

This is for the clean microservice architecture very useful, but less so in case there is more components in a repo (e.g. in case of a vendor supplied repo, that contains say an application and a database)

**Describe the solution you'd like**
The ability to override a component on a stage, e.g. `stageBuildOpenShift(...., "myComponentId")` so people can use multiple containers in one dc later .. (or multi dc) - see https://docs.openshift.com/container-platform/3.7/architecture/core_concepts/pods_and_services.html

**Describe alternatives you've considered**
copying shared lib code into the jenkins file (e.g. https://github.com/opendevstack/ods-quickstarters/blob/master/ds-ml-service/Jenkinsfile.template#L103-L135) - which is not good.

@metmajer  @gerardcl  @buegelbeatz

**Comment by metmajer** [comment]
@clemensutschig Yes!!

**Comment by clemensutschig** [comment]
@metmajer - I see this a ODS 3 features - for june (which would then support sockshop) ... thoughts?

**Comment by michaelsauter** [comment]
Fully agreed, this will be great!

However, I am not sure we should put this into ODS 3 (June). I believe we have some groundwork to do:

* What does that mean for the provisioning app (quickstarters)?
* What is the relationship with the MRO? Right now we do not have a defined contract between the MRO and each component. I believe this to be crucial for something like this to work. This contract would be much easier to establish if the MRO were in the shared lib.
* How does this affect other areas such as environment promotion, JUnit tests, SonarQube scanning, Snyk scanning, etc. There are lots of affected places. Right now I believe we first need to get the building blocks in shape (which I started in #221).
* If we allow multi-deployment configs, maybe we should also allow multiple containers per pod? It's also not possible, and somewhat related. We don't have to do both at once, but it would be good to check if we can find a solution which fits both use cases.

My proposal would be to:

* Get the groundwork done. This is on track for v3, but I really want to avoid building on top of moving, half-ready things. 
* After we have a solid framework in place, discuss how we want to approach it and have the time to think it through.
* Roll this out with v4.

**Comment by clemensutschig** [comment]
I would suggest, ability to build multiple, and deploy multiple - should be given for v3 ... the rest we can discuss :).

**Comment by clemensutschig** [comment]
@buegelbeatz - we need your input here ... you are the mr multirepo :)

I could envision to provide a list of components to the shared lib config, rather than a singular. and we would execute for a first shot, the stages you provide for the contents of the list ... but I want to hear you :)

**Comment by gerardcl** [comment]
Hi! I like this and also find this as a missing piece on the ODS library side, so to be able to manage a monorepo project with different components, yes!
I have been thinking about this also many times and I see two sides (as also mentioned):

1 - to simply provide the functionality of building and rollingout one or many components from the ODS (jenkins shared) library by letting the developers extend the param `componentId` to an object/dict/map that maps `componentId` with `its docker folder` and then passed to `BuildOpenShiftImageStage`, then iterate (default could be as usual one single component map {'componentId': 'docker'}). Same applies for rollout stage.

2 - as mentioned, this should also be provided in the other stages provided by the library. So to be able to define one or many test results folders, sonarqube runs, snyk runs, ... 

Other thoughts, if many components in a monorepo, one might not always want to build and deploy everything, so maybe we shall detect or flag what to do in a per component basis...

**Comment by clemensutschig** [comment]
@gerardcl  - I gave this some more though .. and I think build / scan etc is really a nobrainer (assuming we go with a component list / map) .. deploy is going to be the interesting part ... I guess any of the n components will trigger a redeployment (assume 1 container / n pods)

I think this is also the default setup we would support ... @martsec  - what is your usecase?

**Comment by clemensutschig** [comment]
The other Option is a more building block like Design.. that is a simple param for build/deploy stage and One just calls it multiple times

**Comment by clemensutschig** [comment]
As internal representation for `getArtifactURIs` I could envision
```
"ocp": {
	"builds" : { 
		"myBC" : {
			"buildId" : "myBC-1", 
			"image" : "sha:..." 
		}
	},
	"deployments" : { 
		"myDC" : { 
			"myDC-1" : {
				"myContainer-1" : {
					"image" : "sha:...",
				},
				"myContainer-2" : {
					"image" : "sha:...",
				}
			}
		},
		"myOtherDeploymentConfig" : { 
			"myOtherDeploymentConfig-1" : {
				"myOtherDeploymentConfigContainer-1" : {
					"image" : "sha:...",
				}
			}
		} 		
	}
},
"failedStage" : "build"
```

**Comment by clemensutschig** [comment]
@gerardcl  - the output you get from the new stage - contains also everything you need to get access to the pods

got deploy information [deployment:flask-52, pod:[podName:flask-52-ds7nv, podNamespace:odsst-dev, podCreationTimestamp:2020-04-13T16:48:50Z, podEnvironment:dev, podNode:....., podIp:...., podStatus:Running, containers:[flask:docker-registry.default.svc:5000/odsst-dev/flask@sha256:b6571d7e6154cb2de0bf8993e97bc462651f89888212e489bebf177ac7f62de9]]]

**Comment by gerardcl** [comment]
will take a look! as a first reading looks good!
