### ISSUE TITLE
Remove OWASP support

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#225]
It is only half-finished, and therefore we should not support it. Plus, the same can be achieved with Snyk now.

**Comment by renedupont** [comment]
When we remove this, we can (and should?) also remove some stuff in ods-core (like the cli in the maven image) and I think we create somewhere automatically a volume for this? Once I get time for this I can take a look at the other things.

**Comment by michaelsauter** [comment]
@renedupont Correct. Would be nice to get this done soon so that any testing already includes that change. The Jenkins templates add the PVC somewhere.

**Comment by renedupont** [comment]
@michaelsauter I think this is all: https://github.com/opendevstack/ods-core/pull/556
Or does something come up your mind that is missing?
