### ISSUE TITLE
Refactor Pipeline to use services

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#249]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy

1. https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L217-L248 should be in `bitbucketService`

1. https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L266-L320 should be in `OpenshiftService`

1. https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L182-L215 should be in a new `JunitService` 

@michaelsauter  . can you pick this up - you already started refactoring, and introduced the `BitbucketService` :)

At least the update of the bitbucket commit we will also need in the mro later :)

**Comment by michaelsauter** [comment]
Yes, adding this to my list. I want to do this bit by bit.
