### ISSUE TITLE
Call snyk monitor after test

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-jenkins-shared-library#253]
**Is your feature request related to a problem? Please describe.**
I read here https://support.snyk.io/hc/en-us/articles/360000920818-What-is-the-difference-between-snyk-test-protect-and-monitor- that they advise to call 'monitor' after 'test':

> snyk monitor can be used from the CLI to create a project on the Snyk website that will be continuously monitored for new vulnerabilities. After running this command you will see it by logging in to the website and viewing Your projects. You should run this command regularly in order to update the dependencies for your project. Consider running it as part of your build process after running snyk test, that way we will always know what dependencies you have and can notify you when any of them become vulnerable.

**Describe the solution you'd like**
Call monitor after test. Currently we do it the other way around

**Comment by stitakis** [comment]
sounds good to me
