### ISSUE TITLE
No handling of empty branch to env mapping

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-jenkins-shared-library#262]
**Describe the bug**
![Screen Shot 2020-04-22 at 23 41 54](https://user-images.githubusercontent.com/16910110/80037665-4bfd4e80-84f4-11ea-8943-4ecf89525c6b.png)

**Expected Behavior**
Handle the error instead of printing the stack trace

**Comment by michaelsauter** [comment]
Hmm, this should not have happened. Might be a defect in recent refactoring by myself. If you have questions, please ask.

**Comment by sino92** [comment]
Re-checked the issue, it looks like recent refactoring fixed it. I think I might have used a non updated bitbucket master or maybe another ods branch when the error came up. Closing this issue.
