### ISSUE TITLE
Why dont we infer Project id and component from the git url of the repo instead of coding them into the jenkinsfile?

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#266]
**Is your feature request related to a problem? Please describe.**
I gave our contributor quickstarter some more thought.. and in order to prevent changes to the jenkins file and other pieces (sonar) that one would have to change back before an upstream contribution, we could infer project id and component id directly from the `origin remote url` instead of hard coding them into the jenkins file..

the git url pattern is every time similar (because we create it in the prov app):
http(s)://bitbucketHost/scm/`projectId`/projectId-`componentId`.git

**Describe the solution you'd like**
See above 

**Describe alternatives you've considered**
An unmecessary change commit before upstream push.. Error prone

**Context:**
today: https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Context.groovy#L252-L260

**Comment by clemensutschig** [comment]
@oalyman / @michaelsauter - also related to #265

**Comment by clemensutschig** [comment]
This would also allow us to remove the renderjenkinsfile stage..  Another benefit

**Comment by clemensutschig** [comment]
```
      def origin = "https://..../scm/opendevstack/ods-jenkins-shared-library.git"
    
      List splittedOrigin = origin.split ("/")
      def project = splittedOrigin[splittedOrigin.size()-2]
      def data = [ 
        "project" : project,
        "component" : splittedOrigin[splittedOrigin.size()-1].replace (".git", "").replace("${project}-","")
      ]
```

**Comment by michaelsauter** [comment]
Rendering would still be required I think, as it does a few more replacements, see https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/quickstarter/RenderJenkinsfileStage.groovy#L21.

We should still allow setting the project/component explicitly I think. But we could default to values extracted from the origin URL as you suggest, that would be a nice improvement 👍
