### ISSUE TITLE
MRO should update commits of repos (incl self) it builds with Jenkins build job status 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#278]
Analog to https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L128

**Comment by clemensutschig** [comment]
@michaelsauter - which commits should we update the ones we built from originally or the ones you created during phaseFinalize? Both are ok for me..

**Comment by michaelsauter** [comment]
Ha, good question. I am not entirely sure. When we start the build, we do not know which commits we'll create, so we can only update the build status for the original ones. So I think I would take those.

**Comment by clemensutschig** [comment]
@michaelsauter - we know the created commits as well. And i'll add them to the repo.data so they show up.. (at the end this is what we carry fwd) - so i could easily Update those as well e.g. with 'created by'

**Comment by michaelsauter** [comment]
Sure you know them at the end ... but not at the start. In the component pipeline, we set the build status when the pipeline starts to run to "in progress" - that wouldn't be possible with commits you have not created yet ...

**Comment by clemensutschig** [comment]
For those commits only created.. i would Set success in finalize.. directly

Michael Sauter <notifications@github.com> schrieb am Di., 5. Mai 2020,
08:53:
