### ISSUE TITLE
Run against SonarCloud

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#286]
Every build (Github Actions workflow) should run the code against https://sonarcloud.io to get feedback on source code quality.

While there is an action (https://github.com/SonarSource/sonarcloud-github-action), it says:

> Do not use this GitHub action if you are in the following situations
> * ...
> * Your code is built with Gradle: use the SonarQube plugin for Gradle during the build
> * ...

So it seems we should add a Gradle plugin, and execute that in the workflow.

**Comment by michaelsauter** [comment]
https://sonarcloud.io/documentation/analysis/automatic-analysis/ hints at Groovy not being one of the languages compatible with automatic analysing :(

**Comment by michaelsauter** [comment]
We are creating reports with CodeNarc now - using Sonar might be too big an overlap.

**Comment by clemensutschig** [comment]
We should publish them somehow.. so people see we care

Michael Sauter <notifications@github.com> schrieb am Di., 5. Mai 2020,
17:09:
