### ISSUE TITLE
Set SonarQube project version

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#29]
We should set the version of the project when scanning.

I suggest the following semantics: if `sonar-project.properties` contains the string `sonar.projectVersion=`, then we leave that as is, assuming the user wants to have their own versioning scheme. Otherwise, we set the version dynamically to the Git revision by passing it to `sonar-scanner` like this: `sonar-scanner -Dsonar.projectVersion=sha`.

**Comment by clemensutschig** [comment]
And also branch Name..   can be set.. we should make use of that

**Comment by michaelsauter** [comment]
Sure, we can also set that! It'll only really pay of if one uses the paid multi-branch support of SonarQube, but it's good to set it in any case.

**Comment by michaelsauter** [comment]
OK, after trying to set the branch name, I think we should not do it for now. `sonar.branch` is deprecated (it creates a separate project), and the new `sonar.branch.name` as described in https://docs.sonarqube.org/display/SONAR/Branch+Analysis does not work for the free SonarQube version, you need the branch plugin ...
