### ISSUE TITLE
Retrieve services via context instead of registry?

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#293]
I was thinking if it would be good to remove the `ServiceRegistry`, and instead add getters to the `Context` to retrieve e.g. the `OpenShiftService`.

Pros:
- No separate registry to deal with. Makes testing a little easier
- Services can be lazy loaded (on first access). This avoids having to create the instances initially, and to do fancy stuff like https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/vars/odsComponentStageScanWithSonar.groovy#L9-L17 to make testing possible
- It would allow Jenkinsfile authors to easily access a properly configured service to use in their own stages

Cons:
- Context gets more methods

@metmajer @clemensutschig @oalyman @renedupont Thoughts on this?

**Comment by metmajer** [comment]
@michaelsauter We need to keep that service are injected for testability. Whatever the context those instances come from isn't important. Either way is fine with me.

**Comment by metmajer** [comment]
FYI @s2oBCN @jorge-romero

**Comment by s2oBCN** [comment]
I commented the implementation in the PR https://github.com/opendevstack/ods-jenkins-shared-library/pull/551

**Comment by michaelsauter** [comment]
Just as a side note: I created this issue back then because I felt the current situation is a bit messy. I still think it is, but I'm not sure if and how we should fix it (because of the effort involved). Right now I'm at "personally does not matter that much to me" ... feel free to take this into any direction you see fit, I'm fine either way.

**Comment by michaelsauter** [comment]
OK, there seems to be no solution at the moment which ticks all the boxes without doing a massive refactoring. To avoid confusion, I'm closing this for now.
