### ISSUE TITLE
Codenarc spits out errors during run

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#299]
While Codenarc can still generate the report, it spits out errors like this:
```
None: 63: unable to resolve class org.ods.orchestration.util.PipelineSteps
 @ line 63, column 21.
           def steps = new PipelineSteps(this)
                       ^
```

It would be nice if those errors would not happen, even if they don't seem to hurt.

I googled a bit, found some related issues, but was not able to solve it.

@oalyman any idea how to fix this?

**Comment by oalyman** [comment]
@michaelsauter for which file do you get those reports?

**Comment by michaelsauter** [comment]
It's all over. Just run it yourself: `./gradlew codenarcMain` ...

**Comment by michaelsauter** [comment]
Found the problem: https://github.com/CodeNarc/CodeNarc/issues/123#issuecomment-152676832.
