### ISSUE TITLE
Bitbucket not recognizing last successful build after a failed one

### ISSUE THREAD

**Issue by ManuelFeller** [opendevstack/ods-jenkins-shared-library#300]
**Describe the bug**
We observed that Bitbucket does not allow merges even if the last executed build was successful.

**To Reproduce**
1. Create a PR in a Bitbucket repo where you need one successful build to merge that PR
2. Make sure that PR fails (or cancel it) while Jenkins is executing the build
3. Manually start the build again and let it run through successfully
4. See that the Merge is still not possible

**Expected behavior**
If the last build was successful we would expect that the merge is possible

**Screenshots**
![ods_bug_successful_build_not_recognized](https://user-images.githubusercontent.com/14804960/80711992-8cab2800-8af1-11ea-8c32-73f79a5d0f72.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11 (should be; will update if not)
 - OpenDevStack 2.x (will update if I have the answer)

**Comment by gerardcl** [comment]
Hi Manu.

This is a Bitbucket issue I believe.

Bitbucket expects that the communication is handled via the hooks, but it does not take into account that connections might drop or close for whatever infrastructure reason and you might need to run manually the job in jenkins -> that manual run, althought seen in the builds list in BB, will not be taken into account as the last successful one from BB.

We need to think about this, but I would investigate more the BB side,

**Comment by gerardcl** [comment]
For more information: https://confluence.atlassian.com/bitbucketserverkb/commit-build-status-is-always-red-even-if-other-builds-succeed-779171240.html

**Comment by gerardcl** [comment]
looking on the options maybe we can solve it from a lib point of view, let's discuss that!

**Comment by michaelsauter** [comment]
Yes, I think we can simply use another build key (the commit SHA without the Jenkins build number), which should then allow us to update builds instead of creating a history.

What do you think?
