### ISSUE TITLE
Misleading Documentation In Customizing Slaves

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-jenkins-shared-library#304]
**Is your feature request related to a problem? Please describe.**
`branchToEnvironmentMapping` is a required parameter based on the recent changes. The documentation needs an update below `projectId`. 
![Screen Shot 2020-05-04 at 12 22 53](https://user-images.githubusercontent.com/16910110/80956757-1a448b80-8e02-11ea-9210-97917a1883d9.png)

**Comment by michaelsauter** [comment]
@sino92 yea, the dots should show that, but you are right it would be good to have that there.

**Comment by sino92** [comment]
https://github.com/opendevstack/ods-jenkins-shared-library/pull/305 I've left out the three dots implying that people might add more of the optional ones.
