### ISSUE TITLE
Remove DevelopersRecipientProvider from email list

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#308]
`DevelopersRecipientProvider` causes all people who are involved in commits in a change to be emailed. The changeset includes commits of the shared library. Therefore shared library authors might get an email if something breaks in a project. I don't think that makes sense, and propose to remove this.

Trying to collect information about the email recipients, it seems to me that `CulpritsRecipientProvider` would still contain the authors of the failing commits, so I think it is fine but the documentation is terrible.

@gerardcl @renedupont @oalyman  Thoughts?

**Comment by gerardcl** [comment]
hi! as mentioned in the PR:

followup proposal: expose an ODS Pipeline context param that can enable users to overwrite default recipients to whatever they need (e.g.: msteams channel inbox), single or multiple ones?
shall we go for that too? (separate topic maybe...)
