### ISSUE TITLE
Checking odsComponentPipeline argument input types

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-jenkins-shared-library#315]
**Describe the bug**
Passing an empty list instead of a map type can cause this error. Need to check the object type of user arguments before they make their way to other methods in the shared library. 
<img width="999" alt="Screen Shot 2020-05-05 at 16 32 15" src="https://user-images.githubusercontent.com/16910110/81078693-d5e2e980-8eee-11ea-8f69-8b3c5bf5b34c.png">
Bug available in master.

**Comment by michaelsauter** [comment]
> Passing an empty list instead of a map type

For what argument did you do this?

**Comment by sino92** [comment]
`branchToEnvironmentMapping`

**Comment by clemensutschig** [comment]
I can reproduce this - on latest master ... the problem is the real issue is hidden behind the bitbucket NPE ...
