### ISSUE TITLE
Align slave image config of orchestration pipeline

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#323]
Right now, one can only choose the image tag to use, like this:
```groovy
odsOrchestrationPipeline(odsImageTag: '2.x')
```
The namespace and the image stream which are used are not visible and can only partly be influenced.

This is different to the component pipeline:
```groovy
odsComponentPipeline(imageStreamTag: 'ods/jenkins-slave-base:2.x')
```

I think for consistency, it would be better if the orchestration pipeline would take the same option as the component pipeline - even if most of the orchestration pipeline currently runs on master.

FYI @clemensutschig @oalyman @metmajer

**Comment by clemensutschig** [comment]
@michaelsauter  - why would I want this? ... this makes very much sense for the component world.. for the orchestration - we alsways want to use the slave base, or?

**Comment by michaelsauter** [comment]
@michaelsauter Yes, I think we would almost always want to use the slave base. The main reason to open this issue was just consistency. It would also help developers of the pipeline who want to try different stuff but don't want / can build in the central namespace. Theoretically, users of the pipeline could do some customisations, but I can't think of a situation where one would need them right now. It might be handy if you use make/script steps, as they run right now not in the context of the component - however right now they are executed on the master, they should be moved to the slave then.
