### ISSUE TITLE
Allow repo name which does not follow <project>-<component> pattern

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#327]
Anything that is not `<project>-<component>` does not work. It would be nice to allow to retrieve the repo name (we already read the origin URL, so should be easy), and then set that as the repo name (e.g. to query the BB API).

FYI @stitakis I think that is the master issue with the provisioning app as it is setup in the prov namespaces ...

**Comment by clemensutschig** [comment]
@michaelsauter  - what's the usecase here? we seed the repo names (in the provision app) - so when does / can this happen? ...

**Comment by michaelsauter** [comment]
Right now the prov app in an existing prov-cd/dev/test doesn't work because it does not conform to the convention. Further, the same problem might happen to people that migrate an existing repo to ODS. I think we should help them.
