### ISSUE TITLE
Shared lib should display agent pod events 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#353]
**Is your feature request related to a problem? Please describe.**
sometimes the agent pod bootstrapped - cannot start, for various reasons,.. we should try to get those logs into the jenkins pipeline run.

**Comment by michaelsauter** [comment]
Closed by #385.

**Comment by michaelsauter** [comment]
Actually, #385 solves this for the deployment, not for the agent pod. Leaving this issue open ...

**Comment by michaelsauter** [comment]
It seems like newest Jenkins (2.222) ships with a Kubernetes plugin (1.25) that has this feature built in:
```
‘Jenkins’ doesn’t have label ‘pod-2ffab3a2-687c-47db-b925-e2c68e6d5119’
Created Pod: foo-cd/pod-2ffab3a2-687c-47db-b925-e2c68e6d5119-62kqp-mbgg2
[Normal][foo-cd/pod-2ffab3a2-687c-47db-b925-e2c68e6d5119-62kqp-mbgg2][Scheduled] Successfully assigned foo-cd/pod-2ffab3a2-687c-47db-b925-e2c68e6d5119-62kqp-mbgg2 to ip-172-32-56-200.eu-east-1.compute.internal
[Normal][foo-cd/pod-2ffab3a2-687c-47db-b925-e2c68e6d5119-62kqp-mbgg2][Pulling] pulling image "172.30.22.196:5000/ods/jenkins-agent-golang:3.x"
[Normal][foo-cd/pod-2ffab3a2-687c-47db-b925-e2c68e6d5119-62kqp-mbgg2][Pulled] Successfully pulled image "172.30.22.196:5000/ods/jenkins-agent-golang:3.x"
[Normal][foo-cd/pod-2ffab3a2-687c-47db-b925-e2c68e6d5119-62kqp-mbgg2][Created] Created container
[Normal][foo-cd/pod-2ffab3a2-687c-47db-b925-e2c68e6d5119-62kqp-mbgg2][Started] Started container
```

I think we should close this issue and ensure we move to that base version.

FYI @sino92

**Comment by sino92** [comment]
Ah cool. If I understood right, to enable pod (detailed) logs to be included in the pipeline? 
If that's the case then we can easily catch the `KubernetesClientTimeoutException` error and stop the pipeline.
