### ISSUE TITLE
let build pipeline fail if no environment to deploy was determined

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-jenkins-shared-library#357]
As developer I would like to be able to configure the build pipeline to fail if no environment to deploy was determined. 

Currently in ODS 2.x a build pipeline could end successfuly but no new image is deployed to openshift. 

In such cases this log message can be easily overlooked: 
``` 
'No environment to deploy to was determined [gitBranch=feature/MYAPP-test-deployment, projectId=myapp]'
```

**Comment by clemensutschig** [comment]
@michaelsauter

**Comment by michaelsauter** [comment]
@stitakis In which cases would you want this? Or put another way, in which case do you have an environment for every branch that you can think of?

How did this come up? Was there a typo or so and you were wondering why nothing was deployed? Or how did you run into an issue?

**Comment by clemensutschig** [comment]
close? .. there has been no real outcome, so I vouch to leave as is,

**Comment by michaelsauter** [comment]
Please reopen if you still need this.
