### ISSUE TITLE
MRO Test / Build stage duplicate lots of code

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#359]
**Describe the bug**
code duplication in the two stages ...

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/BuildStage.groovy#L82-L111

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/TestStage.groovy#L125-L154

This should be cleanly refactored into the JunitTestReportsUsecase - to remove clutter from the stages...

Also this jira.XXX https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/TestStage.groovy#L62-L75 should go away

**Comment by clemensutschig** [comment]
@martsec  / @metmajer  - is this something on your plate? - I know this will cause some good test-rework, ... but we should try to get all this clutter out of the stages.

**Comment by martsec** [comment]
That is not on our plate right now

**Comment by clemensutschig** [comment]
Ok - i will do this them with my logger changes

8vicat <notifications@github.com> schrieb am Fr., 29. Mai 2020, 16:04:
