### ISSUE TITLE
Move environment cloning to master node

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#36]
Currently, automatic environment cloning is done via two provided stages, `stageCreateOpenshiftEnvironment` and `stageTriggerAllBuilds`. These are called from each Jenkinsfile on the slave node. However, those stages do not need to be on the slave node, nor do they depend on e.g. build output. Therefore, it would be better to move them into the master node, and just execute them if automatic environment cloning is configured.

Benefits:
* Each Jenkinsfile does not need to call those stages
* Jenkins overview does not show the stages if they are not use

**Comment by michaelsauter** [comment]
I looked into this and realized that `stageTriggerAllBuilds` does not actually work anymore (in `master`). Now that we do binary builds, the `Dockerfile` assumes certain paths that do not hold when built from a Git repository. On the other hand, triggering all builds cannot happen via binary builds as we do not have the sources of the other repos/builds checked out/built. 

@clemensutschig @stitakis @hugowschneider @tjaeschke Thoughts about this? How do we deal with this for 1.0?

**Comment by michaelsauter** [comment]
Further to the above, I realized that even the previous state of `stageTriggerAllBuilds` was broken: when builds are triggered, some branch needs to be assumed from which to take sources. This might not be in line with what should be used (e.g. it might build from the `master` branch, but you cloned the `dev` env which is wired to the `develop` branch ...).

At this stage, this feature is quite broken. Not sure what to do next ... if we disable it, the whole thing is quite difficult to use - since only the project is cloned, but every repo needs to open a new branch that is mapped to the new env, and then trigger a Jenkins build in there.

**Comment by clemensutschig** [comment]
@michaelsauter fix it. Or we need to back it out;-(

**Comment by michaelsauter** [comment]
@clemensutschig Agreed that what we offer should work. The problem is that I don't know how to get it there - what exactly would "it works" be? It never really worked - only with huge assumptions (e.g. that you only want to clone master etc. etc.). 

One "fix" is to not trigger builds. That "works" but is not very usable IMHO. If we want to trigger builds though, I don't know what to implement ...
