### ISSUE TITLE
Revisit cloning support

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-jenkins-shared-library#374]
In https://github.com/opendevstack/ods-jenkins-shared-library/issues/112 @gerardcl  suggested  to remove the clone-script and potentially auto-cloning and instead focus on inter-namespace cloning.

See also https://github.com/opendevstack/ods-jenkins-shared-library/issues/112#issuecomment-639445186

FYI: @michaelsauter @hugowschneider

**Comment by michaelsauter** [comment]
I want to bring this up again. From my perspective, we should remove cloning support:

* The component pipeline feels like the wrong place to do it: cloning affects the project (all components), not just the one component that is being built
* We have similar functionality in the orchestration pipeline using Tailor, so the feature is not orthogonal
* The technical approach feels wrong to me: it's using a bunch of scripts which have proven to be brittle as it is near impossible to cover all edge cases like this (e.g. there are hardcoded string replacements for some URLs).
* It doesn't work anyway in a typical, regulated environment where the `jenkins` serviceaccount does not have `self-provisioner` rights

@clemensutschig @metmajer @hugowschneider @gerardcl @henrjk Would appreciate an agree/disagree so we can move forward with this.

**Comment by henrjk** [comment]
Thank you @michaelsauter for this summary. I agree that it should be removed.
