### ISSUE TITLE
enable multi pod agent orchestrating (optional, default to multi container agent)

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-jenkins-shared-library#387]
**Is your feature request related to a problem? Please describe.**
When running on OpenShift Dedicated, you get nodes limited to 4cores and 16GB of memory. In the case that you need to run different stages based on very different resources (e.g.: E2E tests, nodejs, java, python, ... different frameworks, quality gates,..) within the current ODS framework one can only distribute those containers in the same Jenkins Agent Pod, which leads to very high CPU distribution requests within the cluster (this is because the main atomic unit for resources measurement is up to a Pod level, not to container level); basically the sum of the resources defined by the containers is requested when creating such Agent Pods.

**Describe the solution you'd like**
The current kubernetes Jenkins plugin used in this library seems to offer the option to load more than one Pod.
- kubernetes plugin references: https://github.com/jenkinsci/kubernetes-plugin#pipeline-support
- ODS Jenkins shared lib kubernetes plugin node usage: https://github.com/opendevstack/ods-jenkins-shared-library/blob/ec8adab0f8ae75884e17aac8f99cabf069a044a4/src/org/ods/component/Pipeline.groovy#L211

**Describe alternatives you've considered**
Having dedicated pipeline services if they can run in Pods.

**Additional context**
For details contact @ManuelFeller and @gerardcl

**Comment by michaelsauter** [comment]
How would the shared library know which steps to run on which pod? Right now, there is only one pod, so the whole closure given to the pipeline is executed on that pod.

Couldn't you simply launch a new pod from your `Jenkinsfile` and use it then? Does that really need any specific support by the shared library?

**Comment by gerardcl** [comment]
yes! right! that point is also in the discussion, we just wanted to create this ticket for such discussion and feedback gathering.
a followup question from your point is what would be a good way of doing that and how integrated with Jenkins shared lib dependencies/stages could that be.

**Comment by gerardcl** [comment]
@velcrin @michaelsauter  closing this in favour of using `ods-pipeline` :)
