### ISSUE TITLE
For agents image configuration - check availability of image & set timeout to connect

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-jenkins-shared-library#391]
**Is your feature request related to a problem? Please describe.**
When the ods-pulled image isn't present in a reachable image stream Jenkins keeps looking for it forever. 

**Describe the solution you'd like**
To avoid this, we can introduce a timeout during `podTemplate` or `containerTemplate` configurations. The timeout functionality can be found in the kubernetes [plugin](https://github.com/jenkinsci/kubernetes-plugin) with propertyName: `slaveConnectTimeout`

**Describe alternatives you've considered**
An additional feature would be to check the availability of the entered image name/version. I.e. `jenkins-slave-maven:4.x.` doesn't exist in ODS. Upon receiving this, we can log a warning message saying its not present in ODS library but it might be a non-ODS image present in developer's private registry. If that's not the case at least the logs will help the developer pin down the source of the problem: the timeout happened because the image doesn't exist.

**Comment by clemensutschig** [comment]
@sino92  - love this .. can you make this happen (at least part 1) for ODS 3 ... this would be great!

**Comment by michaelsauter** [comment]
That would be great! Also, if the pod fails to come up, exposing the events would be great! See #353 - the code to do that is 99% there already. If you choose to add this as well, feel free to reach out to me.

**Comment by sino92** [comment]
@michaelsauter Thanks for letting me know that newer Jenkins version displays the pod log output. 
Here's an example of what we get in the logs for a timeout. Will catch the error and display a message about the lack of the searched image for now.
```
bric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [10000] milliseconds for [Pod] with name:[pod-57752291-0efa-4e27-9c31-d7e37e011fad-31mfv-kjgkd] in namespace [foo-cd].
    at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:130)
    at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:131)
    at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:291)
    at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
    at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
2020-06-30 20:50:00.549+0000 [id=522]   INFO    o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent pod-57752291-0efa-4e27-9c31-d7e37e011fad-31mfv-kjgkd
Terminated Kubernetes instance for agent foo-cd/pod-57752291-0efa-4e27-9c31-d7e37e011fad-31mfv-kjgkd
2020-06-30 20:50:00.569+0000 [id=522]   INFO    o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent foo-cd/pod-57752291-0efa-4e27-9c31-d7e37e011fad-31mfv-kjgkd
Disconnected computer pod-57752291-0efa-4e27-9c31-d7e37e011fad-31mfv-kjgkd
```

**Comment by sino92** [comment]
I am afraid even with the timeout leads to job being stuck in a perpetual waiting state. Because Jenkins is continuously trying to recreate the pod that failed.
```
[Warning][jannd-cd/pod-d02dcd4c-0efc-4a4a-8695-f4a42a98f7db-qhf78-nq1zh][Failed] Failed to pull image 
"172.30.21.196:5000/ods/jenkins-agent-nodejs10-angular:4.x": rpc error: code = Unknown desc = Error: image ods/jenkins-
agent-nodejs10-angular:4.x not found
```
Good news is that the plugin has fixed this in a later release by cancelling the job from the build queue. See their issue  497 at their release [page](https://github.com/jenkinsci/kubernetes-plugin/releases/tag/kubernetes-1.24.0) for version 1.24.0.
To speed up the release, we can just close this issue with the addition of timeout. That means the developers can at least see the message in logs as opposed to a forever loading spinning wheel. However the build won't be cancelled and the same message will be repeated.
To avoid that, we'll need to use Jenkins 2.204.6, which supports the kubernetes plugin 1.24.0
Thoughts?  @clemensutschig @michaelsauter

**Comment by michaelsauter** [comment]
@sino92 2.204 is actually the default in v311.219 I think, and later images of RedHat ship with Jenkins 2.222 (they don't work with ODS yet though), which comes with Kubernetes 1.25.

So I am fine with leaving the situation as is. Less code on our side, the better :)

**Comment by sino92** [comment]
Closing this issue. Will create another one which includes a cancellation of the build past timeout.
