### ISSUE TITLE
Remove job from build queue upon agent connection timeout

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-jenkins-shared-library#397]
The timeout leads to job being stuck in a perpetual waiting state. Because Jenkins is continuously trying to recreate the pod that failed with message below:

```
[Warning][foo-cd/pod-d02dcd4c-0efc-4a4a-8695-f4a42a98f7db-qhf78-nq1zh][Failed] Failed to pull image 
"172.30.21.196:5000/ods/jenkins-agent-nodejs10-angular:4.x": rpc error: code = Unknown desc = Error: image ods/jenkins-
agent-nodejs10-angular:4.x not found
```
The [kubernetes](https://github.com/jenkinsci/kubernetes-plugin) plugin has fixed this in a later release by cancelling the job from the build queue. This can be seen in issue 497 at their release [page](https://github.com/jenkinsci/kubernetes-plugin/releases/tag/kubernetes-1.24.0) for at least version 1.24.0.

@michaelsauter 's quote sums up the requirements for the solution:

> 2.204 is actually the default in v311.219 I think, and later images of RedHat ship with Jenkins 2.222 (they don't work with ODS yet though), which comes with Kubernetes 1.25.

**Comment by michaelsauter** [comment]
There is nothing for ODS to do. It all depends on the base image a user defines in their BuildConfig. Say a user picks a RHEL based image with `v3.11.232`, then they get Jenkins 2.222, which ships with Kubernetes plugin 1.25.

**Comment by sino92** [comment]
Ah right, the RHEL/CentOS images provided are tied to OC version. Not sure if this is already part of the documentation, what do you think of laying out which range of versions for services (such as Jenkins, Sonarqube etc.) ODS supports? A question that goes beyond OC version, and to plugins etc.

**Comment by michaelsauter** [comment]
Good point, we can/should add that information. One place to do it is in the configuration sample, which is where people decide which version to use for SQ / Jenkins. That information is already present for SQ (https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L75) but missing for Jenkins.

**Comment by sino92** [comment]
Good to know. To increase visibility, could be even added to Opendevstack front page as a `Supported Service Versions` or ods dev env as this is something important before people get their hands dirty with ODS.
