### ISSUE TITLE
withOpenShiftCluster global var for components?

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#405]
I have come across a use case that wants to execute a second component rollout on another cluster. The idea is as follows:

1. Build image in cluster A
2. Deploy in cluster A
3. Import image from (1) into cluster B
4. Deploy in cluster B

For this to work well, the component needs to control its OpenShift resources as OpenShift templates in the `openshift` directory. But if that is the case, the solution is rather straight-forward. Step 1 and 2 are built-in. Step 3 is possible via the new import image feature introduced in #400. For step 4, one needs a new method, which could look like the following:

```groovy
def withOpenShiftCluster(IContext context, Map config = [:], Closure block) {
    if (!config.apiUrl) {
        error('''Param 'apiUrl' is required''')
    }
    if (!config.credentialsId) {
        error('''Param 'credentialsId' is required''')
    }
    def steps = new PipelineSteps(this)
    def currentApiUrl = OpenShiftService.getApiUrl(steps)
    withCredentials([
        usernamePassword(
            credentialsId: config.credentialsId,
            usernameVariable: 'OPENSHIFT_API_USER',
            passwordVariable: 'OPENSHIFT_API_TOKEN'
        )
    ]) {
        def occuredException
        try {
            OpenShiftService.loginToExternalCluster(
                steps, config.apiUrl, OPENSHIFT_API_TOKEN
            )
            block()
        } catch (ex) {
            occuredException = ex
        } finally {
            def tokenFile = '/var/run/secrets/kubernetes.io/serviceaccount/token'
            OpenShiftService.loginToExternalCluster(
                steps, currentApiUrl, readFile(tokenFile)
            )
        }
        if (occuredException) {
            throw occuredException
        }
    }
}

// Usage:
withOpenShiftCluster(context, [apiUrl: 'https://api.cluster-b.com', credentialsId: 'foo-cd-cluster-b']) {
  odsComponentStageImportOpenShiftImage(context, [imagePullerSecret: 'cluster-a-creds'])
  odsComponentStageRolloutOpenShiftDeployment(context)
}
```

So the feature is very easy to build, but I am wondering if we want to add this to the shared library. It certainly opens a whole bunch of opportunities for people who do not use the orchestration pipeline (e.g. because they don't need docs and/or want to deploy components individually, etc.). However, using `withOpenShiftCluster` would not be compatible with the orchestration pipeline - so if people use `withOpenShiftCluster`, they can't use that component with the orchestration pipeline.

FYI @fkressmann

Thoughts @clemensutschig @metmajer @gerardcl?

**Comment by gerardcl** [comment]
I like it! I am in favour of backing it into, main reason for me is to add/have such functionality and see how it can further evolve. Constraint: to assure that it is fully compatible with the orquestration pipeline (which AFAIK it means using the release manager right? - we might only need to add a checkpoint on the proposal you made I guess, and done)
