### ISSUE TITLE
[component pipeline] Build-only environment

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#410]
**Is your feature request related to a problem?**
The option `branchToEnvironmentMapping` maps branches to environments. If the current branch does not match any environment, no target project in OpenShift is selected, and the stage to build an OpenShift image as well as the rollout stage are skipped. Unfortunately, this means there is no feedback on whether the container image can be built on those branches. And the only way to get that feedback, is to also rollout the image. Before #400, building images for every branch lead to a lot of waste as many images would have been built, but not reused. Now that we can reuse images, it would be nice to specify that images should be built but not deployed.

**Describe the solution you'd like**
We could add a prefix to the environment, like this:
```
branchToEnvironmentMapping: [
  "master": "dev",
  "*": "buildonly:dev"
]
```

Which would tell the pipeline to build & deploy to `dev` on `master` branch, and just build in `dev` for all other branches.

**Describe alternatives you've considered**
* Don't make any change and require that users create a separate env so that they can build & deploy there - that would give the benefit that they also run the image, which is even more proof that "it works". But likely the deployments from different branches would fight over this env, which can lead to weird errors. Also, it would require and extra env - the solution above avoids this
* Some other way of specifying that an env is "build only" ... but so far the proposed one feels best to me

**Additional context**
* This should not interfere with the orchestration pipeline as there the environment is anyway set by the release manager - and would always be build & deploy
* We would need to extend the component context with a flag that tells the pipeline if only build should happen. Should be a relatively small change ...

FYI @gerardcl @oalyman @renedupont @henrjk @clemensutschig @metmajer Thoughts?

**Comment by henrjk** [comment]
Cool would be if one could connect to a private openshift (for example running locally on a developer machine) for local builds and one would still observe build failures etc. However this would be a much bigger effort.

Meanwhile this looks good to me. Some questions I wonder about: 

Will the image build during buildonly go to the registry? 
If it is could this cause inadvertent deployments based on latest tag?

**Comment by michaelsauter** [comment]
@henrjk Interesting idea with the local builds. As you say this would likely be bigger and therefore a separate discussion.

> Will the image build during buildonly go to the registry?

I would say yes. Otherwise we would need to patch the `BuildConfig` to avoid any output image - and I'm not sure that is even possible.

> If it is could this cause inadvertent deployments based on latest tag

The `latest` tag is not applied in `odsComponentStageBuildOpenShiftImage`, but rather later, in `odsComponentStageRolloutOpenShiftDeployment`. So the "build stage" only produces an image which is tagged with the Git commit. That is not deployed anywhere, unless it is referenced by a deploy stage, and then it is OK because that pipeline either builds it's own Git commit, or, if it has the same Git commit, we actually want to deploy the existing image.

**Comment by gerardcl** [comment]
hi! it totally makes sense to have the builds generated, yes!
I like the idea to make it already configurable via the branch to env mapping param, although it could also be a flag in the configs of the build stage too, right? So to have the logic directly mapped into the stage itself.

**Comment by michaelsauter** [comment]
@gerardcl Hmm - how would you envision that to look like? I'm not sure I get how you would do that ...

**Comment by gerardcl** [comment]
sure! I just think on a simple use case that basically "builds always" and/or when "environment" is defined
I understand that having such definition from the branching to env mapping param we can define exactly from which branches we also want to build -> but that I see it being always or specific pattern, and that specific pattern could be also part of the "build always" param in the build stage configs

**Comment by michaelsauter** [comment]
What would "build always" do exactly? In which OpenShift project would it build?

**Comment by gerardcl** [comment]
I was thinking that since we are focusing on -dev namespaces it would always build there. But I see the point on using the branch to env mapping to define where to build.

**Comment by michaelsauter** [comment]
It occurred to me that this feature can already be implemented easily with the current version:
```groovy
odsComponentPipeline(
  imageStreamTag: 'ods/jenkins-agent-golang:3.x',
  branchToEnvironmentMapping: [
    'master': 'dev',
    'release/': 'test',
    'feature/': 'dev'
  ]
) { context ->
  odsComponentStageImportOpenShiftImageOrElse(context) {
    stageBuild(context)
    odsComponentStageScanWithSonar(context)
    odsComponentStageBuildOpenShiftImage(context)
  }
  if (context.gitBranch == 'develop' || context.gitBranch.startsWith('release/')) {
    odsComponentStageRolloutOpenShiftDeployment(context)
  }
}
```

Maybe we don't need explicit support for this?

**Comment by gerardcl** [comment]
I would just then document this possiblity as the one you already did for the feature-suffix based deployments in the dev env. Cool!

**Comment by renedupont** [comment]
Wouldn't it be nice to be able to enter the branches in the config map for the deployment stage, like (sorry for bad groovy):

```
odsComponentStageRolloutOpenShiftDeployment(context, config: [ branchesToDeploy: ['develop','release/']] )
```

and then check them here https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy#L60

For branch values that contain a '/' we would do .startsWith(.../)

**Comment by michaelsauter** [comment]
@renedupont Cool, interesting idea. Just thinking out loud: taking your idea even further, one could remove the global mapping, and have the branches / envs only as params to the stages. Hmm ... on the other hand, wouldn't the original suggestion achieve the result equally well, if not better?

**Comment by renedupont** [comment]
Yes the idea is basically just moving your suggestion (the if clause) from the jenkinsfile (where everyone has to do it) to the shared lib where it then can be documented as a new inbuilt feature.

**Comment by michaelsauter** [comment]
Actually, couldn't we generalise your idea, @renedupont? Every stage takes options, so all options could take a `branch` parameter, that only execute that stage for the given branches. Sonar and Snyk stages already do that, why not extend to all, and handle in the `Stage` superclass?

**Comment by michaelsauter** [comment]
Yes `*` would be the default - which matches current behaviour. I guess the bigger question is how to deal with this in an orchestration context. I am leaning towards respecting it even then ...

**Comment by michaelsauter** [comment]
I believe #497 is the better way to solve this problem. However, a general `branch` parameter (as proposed by @renedupont and now tracked in #448) still makes sense to me, and combines nicely with #497.

I'm going to close this issue in favour of #497.
