### ISSUE TITLE
Add epic grouping to CSD

### ISSUE THREAD

**Issue by martsec** [opendevstack/ods-jenkins-shared-library#414]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adapt LevaDocgen to provide in CSD document the epic information to add an extra level for grouping requirements. This will be done as the official CSD template allows, adding subsections inside the existing sections. 

**Describe alternatives you've considered**
N/A

**Additional context**
Requirement from one of the projects. 

See also https://github.com/opendevstack/ods-document-generation-templates/issues/15 

FYI @metmajer  @jorge-romero  @hrcornejo  @jafarre-viewnext

**Comment by michaelsauter** [comment]
@martsec Is this a surgical fix that will make it into ODS this week? Otherwise please move to 3.1 or 4.

**Comment by martsec** [comment]
This will need to be done for 3.1 or later, true. We planned to release it together but for internal reasons it won't happen. Moving it to 3.1. Thanks for the remainder @michaelsauter

**Comment by metmajer** [comment]
@martsec is this contained in `feature/versioning-docs-support`?

**Comment by martsec** [comment]
Checking the commit messages from the branch, it looks like it is not included @metmajer . What I did include is the support for images in User stories and TechSpecs.

**Comment by metmajer** [comment]
@jorge-romero is this contained in #508 so we can close this issue?

**Comment by jorge-romero** [comment]
Yes @metmajer this feature is contained in #508
