### ISSUE TITLE
Support Jira Versions for document generation

### ISSUE THREAD

**Issue by martsec** [opendevstack/ods-jenkins-shared-library#415]
In order to allow to split features into different versions, and to document only what the product has versus everything it is in Jira, we need to adapt the MRO document generation part to populate the documentation only with the correct data.

**Comment by metmajer** [comment]
Thanks @martsec! This issue has been continued in #508. Closing.

**Comment by metmajer** [comment]
My bad, #508 is the PR that corresponds to this issue. Reopening again.

**Comment by stitakis** [comment]
@metmajer what is the status of this issue? Was it done and can be closed? Or should be moved to OpenDevStack 4?

**Comment by stitakis** [comment]
@metmajer I saw the comment above that this relates to #508. Therefore I'm closing it. Please reopen it if I'm wrong.
