### ISSUE TITLE
Orchestration project fails when jira report endpoint returns report failures

### ISSUE THREAD

**Issue by martsec** [opendevstack/ods-jenkins-shared-library#416]
**Describe the bug**
When the Jira REST interface reports failures, the orchestration Project class fails at resolving jira data references. 

```
{
  "project": {...},
  "epics":{...},
  "reportFailures":["failure 1 description","failure2 description"]
}
```

**To Reproduce**
1. Link to issues in Jira with a not supported link
2. Run the pipeline

**Expected behavior**
Project loading does not fail

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 2.x

**Comment by clemensutschig** [comment]
@martsec - can we get this fixed Next week for ods3?
