### ISSUE TITLE
Do not hardcode repoName (project & componentId) - rather than from origin git url

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#417]
https://github.com/opendevstack/ods-document-generation-svc/blob/master/Jenkinsfile#L20

Falls with:

OpenShift Build unitt-cd/run-documentgensvc-unitt-master-1 from http://bitbucket.odsbox.lan:7990/scm/unitt/documentgensvc.git
Checking out git http://bitbucket.odsbox.lan:7990/scm/unitt/documentgensvc.git into /var/lib/jenkins/jobs/unitt-cd/jobs/unitt-cd-run-documentgensvc-unitt-master/workspace@script to read Jenkinsfile
using credential unitt-cd-cd-user-with-password
Cloning the remote Git repository
Cloning repository http://bitbucket.odsbox.lan:7990/scm/unitt/documentgensvc.git
 > git init /var/lib/jenkins/jobs/unitt-cd/jobs/unitt-cd-run-documentgensvc-unitt-master/workspace@script # timeout=10

.......

SonarQube Analysis-documentgensvc] **** STARTING stage 'SonarQube Analysis' for component 'documentgensvc' branch 'master' ****
[Pipeline] stage
[Pipeline] { (SonarQube Analysis)
[Pipeline] echo
Scanned branches: *
[Pipeline] echo
Long-lived branches: master
[Pipeline] readProperties
[Pipeline] withCredentials
Masking supported pattern matches of $USERNAME or $TOKEN
[Pipeline] {
[Pipeline] sh
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label
Curl --fail --silent --header 'Authorization: Bearer ****' 'http://bitbucket.odsbox.lan:7990/rest/api/1.0/projects/unitt/repos/unitt-documentgensvc/pull-requests?state=OPEN'
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
[SonarQube Analysis-documentgensvc] **** ENDED stage 'SonarQube Analysis' for component 'documentgensvc' branch 'master' **** (took 522 ms)
[Pipeline] }
[Pipeline] // wrap
[Pipeline] stage
[Pipeline] { (odsPipeline error)
[Pipeline] echo
WARN: [documentgensvc] ***** Finished ODS Pipeline for documentgensvc (with error) ***** (took 182670 ms)
[Pipeline] echo
WARN: Error: hudson.AbortException: script returned exit code 22

Which seems to be *unauthorized*
All other quickstarters provisioned.. which also use sq do not have this issue.. (and no pr Check, which leads me to believe sth is wrong with the pr Check curl call)

@georgfedermann fyi

**Comment by clemensutschig** [comment]
Working assumption.. the Problem is context.reponame.. which prefixes the Project Name.. https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/Pipeline.groovy#L71

So if you have custom reponame this does Not work..  

@georgfedermann - what You need to do is 
1. https://github.com/opendevstack/ods-quickstarters/blob/master/tests/be-fe-mono-repo-plain/jenkinsfile_test.go#L31 pass 'unitt-' + Component id and same in
1. https://github.com/opendevstack/ods-quickstarters/blob/master/tests/be-fe-mono-repo-plain/jenkinsfile_test.go#L47

**Comment by michaelsauter** [comment]
@clemensutschig Yes. I added the `repoName` getter so that everywhere we use the repo, we are not hardcoding `project-component`. However, at the time IIRC you were against making the repo name flexible so we assembled `repoName` in a fixed fashion. I would be open to open it up, but either way works for me.
