### ISSUE TITLE
Quickstarter PushToRemoteStage - cannot configure branch to be pushed

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#424]
**Describe the bug**
in selected cases - e.g. the automated tests we want to push a specific branch up - but master is always used, which breaks the tests

we tried to use `branch` in the constructor or the odsQuickstarterPipeline - but that does not work...

@georgfedermann  @michaelsauter - blocker for ods3 test

**Comment by georgfedermann** [comment]
provisioning-app Jenkinsfile stating branch in the the pipeline constructor:

`def odsNamespace = env.ODS_NAMESPACE ?: 'ods'
def odsGitRef = env.ODS_GIT_REF ?: 'master'
def odsImageTag = env.ODS_IMAGE_TAG ?: 'latest'

library("ods-jenkins-shared-library@${odsGitRef}")

odsQuickstarterPipeline(
  imageStreamTag: "${odsNamespace}/jenkins-agent-maven:${odsImageTag}", branch: "${odsGitRef}"
) { context ->

  odsQuickstarterStageForkODS(
    context,
    [odsComponent: 'ods-provisioning-app', branch: "${odsGitRef}"]
  )

  /*
   * see templates in the ods-provisioning-app repository
   */
  odsQuickstarterStageCreateOpenShiftResources(
    context,
    [directory: "${context.targetDir}/ocp-config"]
  )
}`

**Comment by clemensutschig** [comment]
#420 Maybe the fix for this.. at least the jenkins Pipeline part

**Comment by michaelsauter** [comment]
Yes #420 fixes this.
