### ISSUE TITLE
Wrong build status fetched on parallel builds

### ISSUE THREAD

**Issue by segfault16** [opendevstack/ods-jenkins-shared-library#425]
**Describe the bug**
If two branches are built at the same time the wrong build information status is fetched and results in a failed pipeline, e.g.

````
+ oc -n biob-dev start-build frontend --from-dir frontend --follow
Uploading directory "frontend" as binary input for the build ...
.
Uploading finished
[Pipeline] echo
build.build.openshift.io/frontend-592 started
Receiving source from STDIN as archive ...
````
After the docker image was successfully built:
````
Push successful
[Pipeline] }
[Pipeline] // timeout
[Pipeline] sh (Get lastVersion of BuildConfig frontend)
[biob-cd-biobase-core-844] Running shell script
+ oc -n biob-dev get bc/frontend -o 'jsonpath={.status.lastVersion}'
[Pipeline] sh (Get phase of build frontend-593)
[biob-cd-biobase-core-844] Running shell script
+ oc -n biob-dev get build frontend-593 -o 'jsonpath={.status.phase}'
````
and eventually the pipeline times out.

The pipeline should not check the status of the last version of the buildconfig (593 in this case), but the build that was triggered by this pipeline (592 in this case).

Occurs on current master.

**Comment by clemensutschig** [comment]
Not Sure if we can Target this for 3 .. which will release end of the week.. @michaelsauter ?

**Comment by michaelsauter** [comment]
Thanks for reporting!

This is definitely a problem and needs to be fixed, but I don't believe it is super crucial:

* It seems to be an edge case as I haven't seen other reports about this
* Jenkins Pipeline runs within one pipeline are sequential, so this situation does not occur when there is a 1:1 mapping between branches and environments - it can only happen if multiple branches are mapped to the same env

Issue #410 might be affected by this.

I would target this for 3.1 or even 4.0.

**Comment by michaelsauter** [comment]
Some additional things to consider when attempting to "fix" this:

* How would changing this affect interaction with the orchestration pipeline?
* What should we do regarding tagging the built image with `latest`?
* What should happen with the deployment? Skip? Let it fail?
