### ISSUE TITLE
Reintegrating release files into main branch fails for ods-test type components

### ISSUE THREAD

**Issue by martsec** [opendevstack/ods-jenkins-shared-library#429]
**Describe the bug**
In the orchestration (release manager) finalize stage, it tries to merge back to master the state of the deployed pods. This however should only be done for `ods` and `ods-service` type components, and not for `ods-test` since nothing is deployed and the files are not generated. Since it can not find them, the pipeline fails.

Introduced with #393
**To Reproduce**
1. Have a test component
2. Deploy officially to DEV (not as developer preview)
3. Pipeline should fail at the finalize state

**Expected behavior**
RM should not try to merge any of those files back to master for `ods-test`

**Screenshots**
![bug-rm-merge-back-test-component](https://user-images.githubusercontent.com/6894585/88941573-78f69580-d289-11ea-8685-5022911a83b0.PNG)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.0 latest master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Log output here...
```

**Additional context**
This bug blocks the release of ODS 3.0 from our end. 

FYI @segator @metmajer @borja44 @jafarre-viewnext @jorge-romero @georgfedermann @michaelsauter @renedupont

**Comment by clemensutschig** [comment]
@martsec - do you provide a pr?

**Comment by martsec** [comment]
On my way

**Comment by michaelsauter** [comment]
Fixed by #431.
