### ISSUE TITLE
Snyk creates many subproject for Gradle based repos

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#434]
**Describe the bug**
Gradle creates many sub-projects for Gradle based repositories. This seems to be caused by Jenkins running every pipeline in a folder named after the pipeline (e.g. named `foo-cd-bar-123`) - this folder name is picked up for Gradle based projects by the Snyk CLI and passed as the "sub project" parameter. This does not happen for NPM based repos.

For more information, see https://support.snyk.io/hc/en-us/articles/360003817357-Snyk-for-Java-Gradle-Maven-#UUID-3d91eb09-1fcf-e973-89ff-bf24ab0ddfe2.

> Gradle sub-projects
>
> Gradle build can consist of several sub-projects, where each sub-project has its own build.gradle, while the root project is the only one that also includes a settings.gradle file. Sub-projects depend on the root project, but can be configured otherwise.
>
> By default, Snyk CLI scans only the current project (the project in the root of the current folder), or the project that is specified by --file=path/to/build.gradle):
>
> To scan all projects at once (recommended), use the --all-sub-projects flag:	
>   `snyk test --all-sub-projects`
> Note: Each of the individual sub-projects appears as a separate Snyk project in the UI.
> To scan a specific project (for example, myapp):
>  `snyk test --sub-project=myapp`

**Affected version**
OpenDevStack: master, but probably also 2.x

Discovered by @fkressmann

**Comment by renedupont** [comment]
I don't have a solution yet but a couple of things pop up to my mind that might be related:

- in https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/SnykService.groovy#L52 we always have `--all-sub-projects` set, which actually exists only for the specific case of using grade with sub projects. Not sure if we should make that configurable in the jenkinsfile?

- the snyk cli version in the base-agent in @fkressmann cluster is v1.217.3, which is from Aug 20, 2019. Maybe the behaviour is different now with a more recent version?

**Comment by stitakis** [comment]
@renedupont both things that you mention make sense to me, `--all-sub-project` could be made configurable and also update of the snyk cli would eventually solve the issue but needs to be verified

**Comment by renedupont** [comment]
fyi, the closing PR changes the snyk stage in a way that `--all-sub-project` is not included automatically anymore, but offers the option to pass (official) snyk cli flags (e.g. `--all-sub-project` and others) to the stage.
