### ISSUE TITLE
Allow to skip builds

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#45]
Developers might want to skip a pipeline build, e.g. if only documentation changes were made. Other CI systems allow this, e.g. by adding something special to the Git commit message. GitLab uses `[ci skip]`, which we could use as well.

**Comment by clemensutschig** [comment]
+1 like that.

**Comment by michaelsauter** [comment]
The suggested command is `git show --pretty=%s%n%b -s | grep '\[ci skip\]'`, which finds `[ci skip]` (which is used by e.g. Gitlab) in subject or body of a commit message. @akhilsoman @sino92 is one of you keen to take a look into this?

**Comment by akhilsoman** [comment]
@michaelsauter, I could take a look

**Comment by clemensutschig** [comment]
@akhilsoman- 1.10?

**Comment by akhilsoman** [comment]
@clemensutschig yes I guess. I will test it this week and confirm.
