### ISSUE TITLE
Unit test automatic document generation not working in a ODS 3.x project

### ISSUE THREAD

**Issue by jssnull** [opendevstack/ods-jenkins-shared-library#454]
Hi,
I'm testing automatic document generation in an ODS 3.x project, the Jenkins pipeline associated works without errors, but it doesn't generate the unit tests reports properly.

For this test I used an ODS 3.x angular quickstarter.

This is the setup I used for configure it:
Jira test:
![image](https://user-images.githubusercontent.com/12979859/94565904-11010300-026a-11eb-954a-17c029a2f6ab.png)

Jira test issue link to user story that declares used component (angular):
![image](https://user-images.githubusercontent.com/12979859/94566156-50c7ea80-026a-11eb-82ee-fbf79f9c4022.png)

Jira user story:

![image](https://user-images.githubusercontent.com/12979859/94566397-92f12c00-026a-11eb-8d0d-e7433d1e4109.png)

Query to jira API for verifying component association to jira:

![image](https://user-images.githubusercontent.com/12979859/94566769-07c46600-026b-11eb-9504-628e1dbaec6a.png)

Component declared in angular test suite:

![image](https://user-images.githubusercontent.com/12979859/94567296-9638e780-026b-11eb-8b2a-e6057c362a23.png)

Release Manager metadata.yml file repositories section:

![image](https://user-images.githubusercontent.com/12979859/94567519-d9935600-026b-11eb-97fe-1841b4277a05.png)

If we run automatic document generation with this setup it will run with no errors:

![image](https://user-images.githubusercontent.com/12979859/94568059-5aeae880-026c-11eb-9834-3881bbb64b99.png)

It generates the needed Junit XML in the proper folder:
![image](https://user-images.githubusercontent.com/12979859/94568233-88d02d00-026c-11eb-9575-b06691c05152.png)

![image](https://user-images.githubusercontent.com/12979859/94568329-a604fb80-026c-11eb-8912-b558e3587be7.png)

Finally unit test are not properly generated in document output

Do we need to add extra configuration in ODS 3.x project for generate the unit tests documentation?
If not, this is a bug or a feature?

Best Regards

**Comment by borja44** [comment]
@jssnull can we close this issue? Is that one applied into 455 and already tested?
Please confirm :) 

Thanks

**Comment by jssnull** [comment]
@borja44  yes, this is fixed; I'll close it
