### ISSUE TITLE
Add stage to produce / export CNES / SQ report

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#46]
we should execute the cnes report automatically after the SQ review - to have a state (= doc) in the build - and store it on a pvc... this way - each build also solidly contains the exported SQ results.

This should be a quick thing to do - add cnes jar to jenkins master .. and on master node execute cnes export after SQ run - that way we have a PVC from master :)

**Comment by michaelsauter** [comment]
Should work, yes!

**Comment by clemensutschig** [comment]
Also linked to ×20

**Comment by michaelsauter** [comment]
@clemensutschig Thanks for the link. Looks doable, but definitely nothing for v1. We could put that into an 1.1, and release that shortly after v1, so one possibility would be to do the update on prem from 0.1 to 1.1 ....

**Comment by clemensutschig** [comment]
![image](https://user-images.githubusercontent.com/40628552/49863760-43294280-fe01-11e8-9039-e3bbff62e9a7.png)

tested on a local projects .. @michaelsauter - this is what needs to be included into the scanSQ stage
<pre> 
    sq_props = readProperties file: 'sonar-project.properties'
    sonarProjectKey = sq_props['sonar.projectKey']    
    withEnv (["SQ_PROJECT=${sonarProjectKey}"]) 
    {
      withSonarQubeEnv('SonarServerConfig') 
      {
          sh "java -jar /usr/local/cnes/cnesreport.jar -s $SONAR_HOST_URL -t $SONAR_AUTH_TOKEN -p $SQ_PROJECT"
          archiveArtifacts '*-analysis-report.docx*'
      }
    }
</pre>

**Comment by clemensutschig** [comment]
first part of fix:
opendevstack/ods-core#57

**Comment by michaelsauter** [comment]
@clemensutschig Cool. I'll add what is needed in the shared lib.
