### ISSUE TITLE
MRO fails on finalize stage - tailor export

### ISSUE THREAD

**Issue by SHoen** [opendevstack/ods-jenkins-shared-library#460]
**MRO fails on finalize stage**
While creating a release with the MRO pipeline the finalize stage fails with unexpected error: 

```
+ tailor --verbose -n space-dev export -l app=space-be-service
--> exit status 1
Options could not be processed: You need to login with 'oc login' first
script returned exit code 1
```

**To Reproduce**
1. Create 14 services that take some time to build
2. Add this services in the release manager metadata.yml
3. Trigger the MRO pipeline to the dev namespace with a version eg. 0.0.20

**Expected behavior**
Pipeline should finish successful 

**Affected version (please complete the following information):**
 - OpenShift:  3.11
 - OpenDevStack 3.0.0

Additional info
Pipeline run took ~26 minutes

**Comment by clemensutschig** [comment]
yak ... we have to check this, and relogin if needed ... @metmajer  / @michaelsauter

**Comment by clemensutschig** [comment]
@SHoen  - can you provide a little bit of jenkins log BEFORE this happens - just to nail down the exact part

**Comment by SHoen** [comment]
@clemensutschig 

Finalize / be-service
 - 49s

```
DEBUG: [export-ocp-verify-be-service]  (took 616407 ms)
+ oc -n key-dev get dc -l app=key-be-service-o 'jsonpath={.items[*].metadata.name}'
DEBUG: ODS created deployments for be-service: [be-service], all deployments: [be-service]
DEBUG: [export-ocp-verify-be-service]  (took 622144 ms)
+ mkdir -p openshift-exported
DEBUG: [export-ocp-be-service] Exporting current OpenShift state to folder 'openshift-exported'. (took 622350 ms)
+ tailor --verbose -n key-dev export -l app=key-be-service
--> exit status 1
Options could not be processed: You need to login with 'oc login' first
script returned exit code 1
```

**Comment by clemensutschig** [comment]
I am playing around with a fix right now ...

**Comment by michaelsauter** [comment]
Phew. What really puzzles me is why the session would time out at all. My understanding is that the session uses the serviceaccount token in the pod, which is a token which never expires. This is also "proven" to work in the webhook proxy which makes use of the token to make API calls to OpenShift, and the pod of the webhook proxy can live for a very long time. 

So somehow it must not be the token, but some kind of oc/kubectl "cache" that is being cleaned?!

@clemensutschig @SHoen Did you try #461 already against the project that took 26min?

**Comment by SHoen** [comment]
@clemensutschig @michaelsauter The pipeline that took 26 min finished successful with #461 after ~22 min.
