### ISSUE TITLE
allow parameters for timeout and retries for getPodDataForDeployment(String rc)

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-jenkins-shared-library#465]
There are cases when the transition from an image to a container might take longer than the hardcoded 5 times 12 seconds retries.
Therefore it would make sense to keep the default 5 times 12 seconds (=60s) delay initially however it should be configurable within a pipeline definition.

https://github.com/opendevstack/ods-jenkins-shared-library/blob/0d49d03b77042a39ce364a7ce5150af5504972a4/src/org/ods/services/OpenShiftService.groovy#L433-L446

```
.....
[Pipeline] echo
2020-10-01 02:49:35Z Could not find 'running' pod for deployment=xxxxxxxxxxxxxxxxxx - waiting
[Pipeline] sleep
Sleeping for 12 sec
[Pipeline] }
[Pipeline] // stage
.........
.........
[Pipeline] End of Pipeline
java.lang.RuntimeException: Could not find 'running' pod for deployment=myproject-32
	at org.ods.services.OpenShiftService.getPodDataForDeployment(OpenShiftService.groovy:445)
	at org.ods.component.RolloutOpenShiftDeploymentStage.run(RolloutOpenShiftDeploymentStage.groovy:117)
	at org.ods.component.Stage.execute(Stage.groovy:23)
```

**Comment by metmajer** [comment]
@tbugfinder in this context, could you take a look at #901 and provide a similar fix?

**Comment by tbugfinder** [comment]
@clemensutschig had implemented #452  and I'm using increased retries.
Are you looking for increasing default timeout vallues?

https://github.com/opendevstack/ods-jenkins-shared-library/blob/4.x/src/org/ods/services/OpenShiftService.groovy#L428-L439

**Comment by braisvq1996** [comment]
@tbugfinder, we are thinking of having the same approach we have for the Deployment in BuildConfig, retries that can be increased

**Comment by tbugfinder** [comment]
Isn't it already in?

https://www.opendevstack.org/ods-documentation/opendevstack/4.x/jenkins-shared-library/component-pipeline.html#_odscomponentstagebuildopenshiftimage

```
odsComponentPipeline(
  imageStreamTag: 'ods/jenkins-agent-base:4.x',
  branchToEnvironmentMapping: ['master': 'test', '*': 'dev']
) { context ->
  //odsComponentStageScanWithSonar(context)
  odsComponentStageBuildOpenShiftImage(context, [ buildTimeoutMinutes: 62 ] )
  odsComponentStageRolloutOpenShiftDeployment(context, [ deployTimeoutMinutes: 32, deployTimeoutRetries: 34 ])
}
```
