### ISSUE TITLE
Release Manager - Branch naming convention has changed in ODS 3.x

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-jenkins-shared-library#470]
Hi,

I've noticed a slight difference in the branch naming convention when deploying a component to DEV using Release Manager between ODS 2.x and 3.x:

### ODS 2.x
`release/${version}`, i.e: `release/1.0`

![image](https://user-images.githubusercontent.com/15997951/96605210-34155480-12f6-11eb-94c8-e717d2df144a.png)

### ODS 3.x
`release/ods-generated-${version}`, i.e: `release/ods-generated-${version}`

![image](https://user-images.githubusercontent.com/15997951/96604695-ae91a480-12f5-11eb-9a4a-203d98fb0ddd.png)

However, I haven't found where in the official documentation this information is. This is the documentation I have checked:

- https://www.opendevstack.org/ods-documentation/opendevstack/3.x/quickstarters/release-manager.html
- https://www.opendevstack.org/ods-documentation/opendevstack/3.x/update-guides/3x.html

I'd really appreciate if someone could tell me where I can find that information.

**Additional context**
This is the only issue I found with occurrences to "ods-generated": opendevstack/ods-core#484

Update: This [section](https://www.opendevstack.org/ods-documentation/opendevstack/3.x/jenkins-shared-library/orchestration-pipeline.html#_source_code_organisation) of the documentation needs to be updated for 3.x from:

> When a version is given, source code will be taken from a branch release/$VERSION in each repository.

to:

> When a version is given, source code will be taken from a branch release/ods-generated-$VERSION in each repository.

/ cc @metmajer

**Comment by metmajer** [comment]
@felipecruz91 interesting in making a contribution to 3.x and master? If you need help, let me know.

**Comment by felipecruz91** [comment]
@metmajer I can give it a try. Just one more question: what about the current [naming convention](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/util/GitTag.groovy#L75) for the tags?

Should we keep it as it is?

![image](https://user-images.githubusercontent.com/15997951/96734708-19f17a00-13bb-11eb-85f3-0839bf4160ee.png)

**Comment by michaelsauter** [comment]
I don't really see how `release-ods-generated/` is that different to `release/ods-generated-`.

On the other hand, I liked `release/{version}` as it was in ODS 2.x. AFAIK there is no problem if the user creates such a branch manually, before the release manager creates it. The orchestration pipeline anyway detects if the branch exists already, and creates/updates as necessary.

For tags I think it is good to have those indicating that they are ODS generated.

**Comment by metmajer** [comment]
@michaelsauter @felipecruz91 I somehow got onto a wrong path when making my proposal. Obviously, the `release/` prefix is good practice, and we should not go without it. I would also favor the solution from ODS 2.x.

@felipecruz91 The change starts [here](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/GitService.groovy#L9), but if we want to name branches and tags differently, then let's introduce a second constant and use them in `getReleaseBranch` and `readBaseTagList`, respectively.

Additional thoughts, @michaelsauter?
