### ISSUE TITLE
Do not execute the whole component pipeline in an orchestration context (?)

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#479]
As of ODS 3, the orchestration pipeline executes the `Jenkinsfile` of a component during the BUILD phase when the target environment is DEV. This means that deployment of the component is driven by the component pipeline when deploying to DEV, but driven by the orchestration pipeline when deploying/promoting to QA and PROD.

I see a few issues with this approach:

* Configuration can be confusing, e.g. the deployment timeout configured on the `odsComponentStageRolloutOpenShiftDeployment` has an effect when deploying to DEV, but has no effect when deploying to QA/PROD (because the stage isn't executed at all).
* The phases of the orchestration pipeline are confusing, as the BUILD phase actually deploys to DEV, but for QA and PROD deployment happens in the DEPLOY phase.
* It can happen that for DEV, the deployment of some components succeed while others fail already while building the container image, leaving the project in an inconsistent state. It would be better if no deployments would happen at all if one of the components cannot be built properly. 

With those thoughts in mind, I came up with the following suggestion:

What if the orchestration pipeline would also deploy components to DEV during the DEPLOY phase? To make this happen, the component pipeline would have to skip the `odsComponentStageRolloutOpenShiftDeployment` if called from an orchestration context, and the DEPLOY phase would need to be enabled also when the target environment is DEV. As a result:

* All deployments triggered by orchestration are done in the same fashion, which means issues with configuration etc. are already detected during WIP builds
* All components have to successfully build before the first of them is deployed
* The BUILD phase of the orchestration pipeline actually only builds (instead of build+deploy), making it easier to understand
* The component pipeline is only there to create artefacts, not to deploy them anywhere. This makes it a bit easier to maintain: right now we have to think how some aspects of `odsComponentStageRolloutOpenShiftDeployment` should behave in an orchestration context - with the suggestion, the whole thing can simply be skipped. 

The downsides of my suggestion I see so far:

* It's a bit of work to do, although not a lot
* It might also require some explanation that only part of the `Jenkinsfile` is executed
* If users have custom deploy logic in the `Jenkinsfile`, it would not be skipped but executed. While this is not great, it would just mean that the deploy to QA step would fail, which is the same situation as we have right now when custom deploy logic is used

Last but not least, I wanted to share a little bit of the bigger picture which is forming in my mind:

Doing the suggested change could be the first step to a world where the `Jenkinsfile` is not executed at all in an orchestration context. This would dramatically simplify the logic, make things way easier to understand for users, and speed up things considerably. In that world, the artefacts would be created ONLY in the component pipeline, and the orchestration pipeline would simply collect / package / deploy those artefacts. For example, the component pipeline already builds a container image for a certain Git SHA. In theory, there is no need to rebuild that image in the orchestration pipeline. The only reason we do this is because we also need the test results, the SonarQube report, etc to create the validation documents. If the component pipeline would store the test results etc. in a place where the orchestration pipeline has access to, the orchestration pipeline could avoid executing the `Jenkinsfile` completely, and just create a "deployable package" of each component by collecting all pre-built artefacts. I haven't thought this through yet completely, but it seems like an interesting direction to explore for me.

@metmajer @martsec @clemensutschig @henrjk @oalyman @felipecruz91 Would be interested to hear your thoughts on this :)

**Comment by henrjk** [comment]
Nice writeup! I have not yet actively used the orchestration pipeline. When reading your suggestions and thoughts,  points I was thinking about are:

1. Would the component pipeline still have deployment responsibilities? Or would one always use the release manager for that?
2. Does the release manager allow having e2e testing so that the 'final' promotion only happens when the tests agains the 'preliminary' deployment succeed? 
3. When using a monorepo with several components could the deployment still be partitioned within the same namespace for feature branches?

**Comment by michaelsauter** [comment]
Thanks. In regards to your comments/questions:

1. I think component pipeline always needs deployment responsibilities, because I would not like to mandate the use of a release manager for everyone. IMHO too much complexity for those that don't need it ... anyway, I think my thoughts above could be summarised as "DEV deployment by component pipeline, promotion to QA/PROD by orchestration pipeline"
2. The release manager allows to have a "test component" which can run smoke tests. However, to my knowledge, whether this fails or succeeds has no effect on the actual deployment. Partially this is because the way how we deploy is actually by replacing the existing resources. So there is no "preliminary" deployment (e.g. a blue/green deployment scenario). In theory this is possible using Kubernetes, but I guess we would need to come up with a concept how to do it.
3. IIRC the release manager deployment already supports N deployments per repo, and for each deployment N containers. So this should be untouched by my proposal here.

**Comment by henrjk** [comment]
To me your proposal makes a lot of sense.

**Comment by serverhorror** [comment]
> Doing the suggested change could be the first step to a world where the Jenkinsfile is not executed at all in an orchestration context

We have a case where we, not only, deploy to OpenShift but to other targets as well. I believe this is what you consider "custom deploy logic".

We are already in a situation where we have trouble using release manager the way it is intended to because of this behaviour. Is there a way to still execute "custom deploy logic"?

These are the cases I can think of:

* Deploy to something completely different than OpenShift (AWS CloudFormation/terraform)
* need to run "custom logic" on 3rd-party systems.

  Think: Running a software installation on a custom device. E.g. pushing new code to a lab robot or CNC machine. A workaround _could_ be to use something like an initContainer or other container and run code in there. But seems ... weird.


So how would one run logic that is outside of the deployable, but still required for the system to actually be deployed?

**Comment by metmajer** [comment]
@michaelsauter I cannot go over the entire issue at the moment, but we plan to use Quickstarters for a variety of target platforms. A limitation to OpenShift will put those ideas to a halt.

**Comment by clemensutschig** [comment]
actually - the "dead code" around `scripts` to be called in phases would help this a lot .. @michaelsauter 

related to #555

**Comment by michaelsauter** [comment]
@serverhorror Thanks for the input. In the meantime I have a few other ideas in this area. I'm going to close this issue for now ... I might open another suggestion in the future once things are more concrete.

**Comment by michaelsauter** [comment]
@metmajer @clemensutschig Sorry didn't see your comments earlier for some reason. What you both point out makes a lot of sense and is aligned with what I'm thinking as well right now.
