### ISSUE TITLE
output link to OpenShift build and image in jenkins build log

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#48]
After the build in OpenShift finishes, we should put the link to the build and, if the build was successful, to the new image into the Jenkins pipeline log.

**Comment by clemensutschig** [comment]
@michaelsauter @renedupont 
openshiftUrl=$(curl -H "Accept: text/html" $API_HOST | cut -d "\"" -f2)

gives you the console url --- that way we have the link to the build (and image)

and then for the build attach
/project/$project/browse/builds/$bc/$buildName

and for the image attach
project/$project/browse/images/$imageName/$imageTag

**Comment by clemensutschig** [comment]
<pre>
def ocAPiUrl = sh(returnStdout: true, script: 'oc project ${PROJECT}').trim()
ocAPiUrl = ocAPiUrl.substring(ocAPiUrl.indexOf("http")).replaceAll("\".", "")
def ocConsoleUrl = sh(returnStdout: true, script: 'oc get route --no-headers | sed \'s/  */ /g\' | cut -d \' \' -f2').trim()
println ocConsoleUrl
<pre>

get api & console URL :)

**Comment by clemensutschig** [comment]
I think we should leave it - and just output the api host - because this is where the lib did the update / tagged / built etc ... 

that is super super easy .. and a surgical fix

**Comment by michaelsauter** [comment]
What is it that we actually want to do here now? We already output `openshiftHost:https://openshift.default.svc.cluster.local`. Not sure what other info we can get reliable via the `oc` binary ...

I'd vote for closing this actually, unless we can get reliable links to the console ...

**Comment by michaelsauter** [comment]
Closing this as it seems that we have no access to the console web UI from the `oc` binary.
