### ISSUE TITLE
(secret replication) Jenkins pipeline sometimes fails after a git merge

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-jenkins-shared-library#482]
**Describe the bug**
After a git merge the Jenkins pipeline fails, saying that it cannot find the credentials "cd-user-with password".
This does not happen in every git merge, and if we execute the pipeline again it ends succcssfully.

**To Reproduce**
1. Make a git merge into your quickstarter repository
2. Check if the pipeline show the error

**Expected behavior**
The pipeline should always find the credentials "cd-user-with-password"

**Affected version:**
 - OpenShift: 3.11
 - OpenDevStack 2.x and 3.x

**Log output here:**

Warning: CredentialId "<projectKey>-cd-cd-user-with-password" could not be found.
Cloning the remote Git repository
Cloning repository RepoURL/projectKey/projectKey-dockplain.git
 > git init /tmp/workspace/projectKey-cd/projectKey-cd-dockplain-master # timeout=10
Fetching upstream changes from RepoURL/projectKey/projectKey-dockplain.git
 > git --version # timeout=10
Setting http proxy: proxy:port
 > git fetch --tags --progress RepoURL/projectKey/projectKey-dockplain.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress RepoURL/projectKey/projectKey-dockplain.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: Authentication failed for 'RepoURL/projectKey/projectKey-dockplain.git/'

**Comment by michaelsauter** [comment]
@henrjk You saw this as well, right?

I have also seen this behaviour at times, with no idea why. Maybe something with the openshift sync that is wrong?

**Comment by henrjk** [comment]
Yes in our project we presumably the same issue. One other symptom I noticed is the following.

## Error displayed in section Global Pipeline Libraries

When the error happens: 

Go to your Jenkins web URL and then  -> Manage Jenkins -> Configure System
Scroll down to the section Global Pipeline Libraries.

- For the Library Name `ods-jenkins-shared-library` Under the box for the where it says Default version `3.x` it showed<br>  :warning: _Cannot validate default version_ 
- In the Source Code Management/Git section a bit lower the dropdown in the Credentials said `- current -` and underneath it said :warning: Cannot find any credentials with id `{{project-name}}-cd-cd-user-with-password`.

Notice that when I checked what is listed in the drop down only the credential `{{project-name}}-cd-cd-user-token` was available, although both were defined at `https://{{jenkins-url}}/credentials`.

I tried changing the credential used to the `*-user-token`.
Places I made changes where the Manage Jenkins page, but also in the openshift pipeline for the developer builds and also in the respective sections inside Jenkins.   So far this did not resolve the issue.

**Comment by clemensutschig** [comment]
Wheb this happens you check the build config that is the source für the build?

**Comment by henrjk** [comment]
I believe the build config of the develop pipeline to which the changes are being merged is not changed when this happens. But next time we see the issue I will double check and report back here.

**Comment by felipecruz91** [comment]
Hi, as days go by, more users have reported this issue. Is there any update or something I can help you with to investigate it further?

**Comment by clemensutschig** [comment]
hey @felipecruz91  - the next time this happens, take a look at
- the build config (in the *-cd namespace) for the pipeline
- take a look into jenkins (secrets) - and see if its there ...

maybe related to 
openshift/jenkins-sync-plugin#359

**Comment by henrjk** [comment]
Last time this happened in our context the build config yam of the pipeline looked fine. When I rebuild the resource version is increment but otherwise nothing changes in the pipelines yaml.

**Comment by felipecruz91** [comment]
@clemensutschig @henrjk I've tried multiple times throughout the day and some of them worked, some others didn't.

See below the useful information that I got from a _failed_ Jenkins build as a result of merging a feature branch into the `test` branch:

**Jenkins logs**
```
+ git lfs
[Pipeline] checkout
Warning: CredentialId "*****-cd-cd-user-with-password" could not be found.
Cloning the remote Git repository
Cloning repository http://*****.com/scm/*****/*****-*****.git
 > git init /tmp/workspace/*****-cd/*****-cd-*****-test # timeout=10
Fetching upstream changes from http://*****.com/scm/*****/*****-*****.git
 > git --version # timeout=10
Setting http proxy: appaccess-zscaler.boehringer.com:80
 > git fetch --tags --progress http://*****.com/scm/*****/*****-*****.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress http://*****.com/scm/*****/*****-*****.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: Authentication failed for 'http://*****.com/scm/*****/*****-*****.git/'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
````

**Jenkins configuration**

![image](https://user-images.githubusercontent.com/15997951/100104754-ddf07f80-2e66-11eb-9e00-0bd3994fc1a5.png)

Notice the warning "Cannot find any credentials with id *****-cd-cd-user-with-password"

![image](https://user-images.githubusercontent.com/15997951/100105390-96b6be80-2e67-11eb-9119-5d656c4b801b.png)

Notice the credential "*****-cd-cd-user-with-password" is not shown as an option in the dropdown.

The secret is listed in OpenShift:

![image](https://user-images.githubusercontent.com/15997951/100105853-1c3a6e80-2e68-11eb-9b7e-8a4a3644f68f.png)

The Jenkins credential is sync:

![image](https://user-images.githubusercontent.com/15997951/100105995-468c2c00-2e68-11eb-8da1-bcfefde0c5c1.png)

The BuildConfig associated to the pipeline contains the `sourceSecret`:

```yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: *****-test
  namespace: *****-cd
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: test
      uri: 'http://*****.com/scm/*****/*****-*****.git'
    sourceSecret:
      name: cd-user-with-password
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - generic:
        allowEnv: true
        secret: *****
      type: Generic
```

**Comment by felipecruz91** [comment]
Adding the following label to the `cd-user-with-password` secret in the `-cd` namespace seems to have resolved the issue (so far):

```yaml
  labels:
    credential.sync.jenkins.openshift.io: 'true'
```

**Comment by michaelsauter** [comment]
@felipecruz91 Good idea! I don't see harm in doing that and it's nicely circumventing the problem. Maybe worthwhile to include in 3.1 if this really prevents the issue from happening again?

**Comment by clemensutschig** [comment]
hmmm - the template for the secret is here
https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/deploy/jenkins-master.yml#L66-L75 

we should add this .. @michaelsauter?

**Comment by clemensutschig** [comment]
@felipecruz91  - do you fix it?

**Comment by felipecruz91** [comment]
@clemensutschig Sure, let me create a PR for this

**Comment by henrjk** [comment]
I added the suggestion by @felipecruz91 in our context as well and will watch whether it fixes the issue for us as well.
