### ISSUE TITLE
[component pipeline] Allow deployment via Helm

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#495]
**Is your feature request related to a problem?**
We support deployment of OpenShift Templates via [Tailor](https://github.com/opendevstack/tailor) at the moment. We do not have support for [Helm](https://helm.sh) because a) it used to require a privileged Tiller in v2 and b) it did not work with all OpenShift resources (such as BuildConfig, Route) in OpenShift v3.11. That said, OpenShift 4.3+ has full support for Helm, and offers a nice integration of Helm releases. Because of this and the widespread use of Helm in the community, we should support Helm in ODS.

**Describe the solution you'd like**
Add Helm as an alternative to Helm in ODS 4. Recommend Tailor for OpenShift 3.11, and Helm for OpenShift 4. Remove support for Tailor in ODS 5, and rely on Helm only then.

**Describe alternatives you've considered**
[Kustomize](https://kustomize.io) is also a popular, tightly integrated way to specify Kubernetes resources. Potentially we should support this as well, but I see Helm as having higher priority.

[Operators](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/) offer another way of packaging Kubernetes applications, and therefore have some overlap with Helm. However operators are more suited towards services which have a complex lifecycle (e.g. databases). Helm is probably a better fit for typical applications.

**Additional context**
In terms of process, Tailor and Helm are quite similar: 1) render resources, 2) apply resources. Therefore it should be relatively easy to integrate.

However, Helm has a few concepts that Tailor does not have, and we need to think about how we deal with those. E.g. the concept of "release", "package" and "rollback" are not present in Tailor.

On the other hand, Tailor has a few concepts that Helm does not have, e.g. diffing (could potentially be provided by [helm-diff](https://github.com/databus23/helm-diff)), secrets encryption (could potentially be provided by [helm-secrets](https://github.com/zendesk/helm-secrets)), preserving paths (not sure if there is a way to do this) and exporting live configuration (also not sure if there is a way to do this - but maybe that is a good thing? 😉).

For users who currently use OpenShift Templates, [template2helm](https://github.com/redhat-cop/template2helm) should provide a nice way to convert to Helm templates.

To support Helm, we need to look at two related, but separate topics: support in the component pipeline, and support in the orchestration pipeline. We should start with the component pipeline first.

FYI @segfault16 @serverhorror @gerardcl @henrjk @segator @metmajer @clemensutschig

**Comment by segator** [comment]
helm and kostumize can life in parallel depending of the complexity of the application under deployment.
Operators should only be deployed using helm.
What i'm worried is how will be the transition of current projects that are using tailor to helm?
how this affects to release manager, if i'm not wrong release manager is exporting resources from test environment to dpeloy to prod, I think should be better if all the projects are forced to have their resource definition in the git repo independenly if we deploy to D,Q or prod.

**Comment by michaelsauter** [comment]
> helm and kostumize can life in parallel depending of the complexity of the application under deployment

Agree. Let's look at kustomize later.

> Operators should only be deployed using helm.

Agree - though we need to get more experience with operators to see how they fit into ODS. For now my thinking is they are simply a resource like any other, and can be deployed via Tailor/Helm/.

> What i'm worried is how will be the transition of current projects that are using tailor to helm?

As mentioned, `template2helm` allows to convert templates. In the end, OpenShift Templates are very similar to Helm templates - they both define the same Kubernetes resources. So users that move to an OpenShift 4 cluster may choose to also convert their templates, at which point the shared library automatically uses Helm to deploy.

> how this affects to release manager, if i'm not wrong release manager is exporting resources from test environment to dpeloy to prod, I think should be better if all the projects are forced to have their resource definition in the git repo independenly if we deploy to D,Q or prod.

Well the release manager offers the "export of live configuration" feature, but it does not require it to work. If the resource definitions already exist, it just makes use of them. How Helm could offer  "export of live configuration", I don't know yet. Personally I think exporting live configuration on the fly will always be tricky and buggy. I'd always recommend defining your resources upfront, and personally would be very happy to enforce this. But this is an area where we need to collect more feedback from users.
