### ISSUE TITLE
[component pipeline] Build images in *-cd projects

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#497]
**Is your feature request related to a problem?**
We run the Jenkins Pipeline in the `*-cd` project, but trigger builds for the components in the `*-dev` and `*-test` namespaces. This has a few downsides:

* We need a `BuildConfig` in both `*-dev` and `*-test`, and need to keep them in sync
* We need `*-dev` and `*-test` projects on the cluster which hosts the `*-cd` project. If we would also build the image in the `*-cd` project, we would not need `*-dev` and `*-test` projects at all on the same cluster. This is relevant for #496. It would also open up the possibility of having a "build cluster" and a "runtime cluster". 
* We need to have resolved an environment to actually build the image at all, see #410. Moving the image building to the `*-cd` project solves #410 in a very different, easy way.

**Describe the solution you'd like**
Build image in the `*-cd` project, and then move the image during deployment to the relevant target cluster/project.

**Describe alternatives you've considered**
Keep as it is.

**Additional context**
All quickstarters use the same `BuildConfig` and `ImageStream` definition, and we patch the `BuildConfig` in the build stage to e.g. have the right labels. Therefore, we could easily create those resources in the `*-cd` project if they don't exist yet. The component authors then don't have to care about the definition at all. Further, in the future we will probably not have `BuildConfig` resources at all, and e.g. use OpenShift pipeline tasks that use tools such as Buildah or Kaniko to build images.

**Comment by michaelsauter** [comment]
Note: This somewhat depends on removal of auto-cloning. Building the images in `*-cd` requires to have `image-puller` permissions from the `*-dev`/`*-test`/etc. namespaces, and those can only be given through `admin` permissions, which the `jenkins` serviceaccount does not have on the `*-cd` namespace.

**Comment by gerardcl** [comment]
I like this idea, so this would mean sharing the same buildconfing/imagestream for all, which make sense since we target tagging by the related git, then we distributed to wherever deploymentconfig/deployment. And, I am totally in favour of removing autocloning functionality and push for preview/clone envs within dev (which is already hinted in the docs and works like a charm in our project!)
