### ISSUE TITLE
Deploy phase of Release Manager fails in case of component type 'ods-service' (missing tailor binary)

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-jenkins-shared-library#499]
**Describe the bug**
This is a very similar issue to opendevstack/ods-core#841 with the main difference that it occurs for the component type `ods` (as defined in the metadata.yml of the **Release Manager**).

**To Reproduce**
1. Go to the Jenkins orchestration pipeline
2. Click on Build with Parameters (deploy to DEV)
3. See the error in the log.

**Expected behavior**
The Jenkins orchestration pipeline should take the component type as `ods` (from the Release Manager metadata.yml file) instead of `ods-service` (from the component's metadata.yml file)

**Screenshots**

This is very misleading because the Jenkins logs show the following message:

```
￼DEBUG: Repository type 'ods-service' configured on '****' thru component's metadata.yml
```

and the component type is actually defined in two places:

In the component's metadata.yml file (these are the default values by the quick starter):
![image](https://user-images.githubusercontent.com/15997951/99983510-39116c00-2dac-11eb-99ba-2bfaf16d7b3d.png)
 
and in the Release Manager's  metadata.yml file:
![image](https://user-images.githubusercontent.com/15997951/99983594-56463a80-2dac-11eb-82ae-bcf138fd9569.png)

So it's not clear why there are _two_ places where the component type can be defined neither which one is predominant over the other.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
+ tailor --verbose -n ****-dev export -l app=****
/var/lib/jenkins/jobs/****-cd/jobs/****-cd-****-mro-pipeline-master/workspace/repositories/****/openshift-exported@tmp/durable-416e17b8/script.sh: line 1: tailor: command not found
```

**Comment by clemensutschig** [comment]
@felipecruz91  -. this is fixed on 3.x (after 3.0) - 
https://github.com/opendevstack/ods-core/blob/3.x/jenkins/master/Dockerfile and also on master ... 

the codebase for what you describe above takes the one from the component - https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/util/MROPipelineUtil.groovy#L192
