### ISSUE TITLE
how "promote to P" affect DEV environment

### ISSUE THREAD

**Issue by petod108** [opendevstack/ods-jenkins-shared-library#540]
**Describe the bug**
We use ODS2.X
In are workflow "promote to P" there are executed E2E tests.
Those E2E tests are executed over edpp-dev environment (back, front, mongodb)
But during execution, backend running on DEV and it's connection to MongoDB has a lot of problems.
Seems like network do not allow connection to mongodb during execution of Realman for workflow "promote to P".
There are lot of errors during E2E execution. And every 1 per 20 execution there is success. Randomly.
What is different "promote to P" with "promote to and release on Q" and "developer preview"????
Because during workflow "promote to and release on Q" and "developer preview" there were no problems.

**To Reproduce**
1. Go to Jira ticket "1" and click "release to P"
2. Check Jenkins job
3. wait when E2E tests started (which actually always run with URLs of application on DEV environment)
3. check backend LOG en DEV environment where is running
4. there are a lot of BackEnd error logs
5. E2E random errors

**Expected behavior**
Should have same result as developer preview and "promote to and release on Q" 

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: v3.11.219
 - OpenDevStack 2.X

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**

**Additional context**

**Comment by clemensutschig** [comment]
Promote to production needs a dedicated (Created) namespace on a cluster .. can you paste some of the errors you get - because I would assume? that the db you are using in bootstrappend thru the release manager in all namespaces .. maybe there is data missing? It's hard to tell from the small description above..

**Comment by metmajer** [comment]
@petod108 I agree with @clemensutschig that your testing environment is not set up properly, most likely. The base URL for the application that points to the environment automatically gets injected into the test framework. Please connect with our onboarding team and put me and Clemens in CC so we can support your way to P with the support from the community.

Peter, also consider that you don't give us too many options at the moment to provide help. A bug always needs to contain a full log of the Jenkins pipeline. In this case, you want to replace any references to boehringer with acme.com or similar. Good news is that other application owners are using this feature successfully, so I expect this to be a more or less easy fix.

**Comment by michaelsauter** [comment]
> We use ODS2.X

Could this be an issue @metmajer @clemensutschig?

Maybe the `Jenkinsfile` doesn't expose the app domain?

**Comment by clemensutschig** [comment]
2.x -> https://github.com/opendevstack/ods-quickstarters/blob/2.x/e2e-spock-geb/Jenkinsfile.template#L45

and btw ... why ods2 :)

**Comment by petod108** [comment]
Thank you.
Could you add to QuickStarter  for E2E in application properties something like:
# Base url with the application to test
# config.application.url=https://<your-app>.${openShiftPublicHost }.api

**Comment by metmajer** [comment]
Hi @petod108! For this, we would need to understand why our current solution is not good enough for you.

**Comment by metmajer** [comment]
@petod108 after our call you should be all set to move forward. If not, let us know here. I will take note to provide an example showing the use of `OPENSHIFT_PROJECT` and `OPENSHIFT_PUBLIC_HOST` into the quickstarter's `application.properties` file.

**Comment by petod108** [comment]
@metmajer I have question how to deal DB during /after testing
How to clean up DB after E2E testing?
Use direct access to DB from E2E project? (works only on DEV and QA, but not in PROD)
Or add extra APIs for DB clean-up in the Backend?
Is possible to use another DB during execution E2E?
Should we ignore most of tests when "promote to P"???
(Because in PROD we should not add dirty test data)

**Comment by metmajer** [comment]
@petod108 this is a question related to your test strategy. Good practice suggests that any traces your tests have created are removed once the tests have executed. Spock supports a cleanup: method you could use for this: http://spockframework.org/spock/docs/1.0/spock_primer.html.
