### ISSUE TITLE
Jenkins Skips build if `[ciskip]` is anywhere in merged commits

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-jenkins-shared-library#556]
The check whether to skip a build skips merge requests if _any_ build in the merge request was marked to be skipped.

Example:

```
Merge pull request #13 in ODM/odm-components from feature/ODM-459-aws-branch-cleanup to feature/ODM-458-refactor-aws-rollout* commit '19cbe34805bc2de615dd4518af7ef463700fbe43':
  ODM-459 Dummy change
  ODM-459 [ciskip] Dummy change
```

When merging this is not being built in the parent branch even though `ODM-459 Dummy change` was the last commit, and has been built in the feature branch. And `ODM [ciskip] Dummy change` was the _first_ commit in the feature branch.

I would expect a merge request to always build or at least use the last state, rather than "if any previous build was skipped I will skip this too"

Changing the referenced lines to `git show --pretty=%s -s` from `git show --pretty=%s%b -s` would solve this.

```
git show --pretty=%s -s
Merge pull request #13 in ODM/odm-components from feature/ODM-459-aws-branch-cleanup to feature/ODM-458-refactor-aws-rollout
```

https://github.com/opendevstack/ods-jenkins-shared-library/blob/68a7a0895a09171813e8d5066879fde97ccb1807/src/org/ods/services/GitService.groovy#L127-L133

**Comment by clemensutschig** [comment]
Nice Martin.. do you send a PR?

Martin Marcher <notifications@github.com> schrieb am Fr., 8. Jän. 2021,
21:02:

**Comment by serverhorror** [comment]
I just might. Need to finish the stuff in my current context first :)

**Comment by michaelsauter** [comment]
Suggestions sounds good to me 👍 Please adjust the docs as well to reflect the change from "message" to "subject": https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/docs/modules/jenkins-shared-library/partials/odsComponentPipeline.adoc#skipping-pipeline-runs.
