### ISSUE TITLE
[bug]: extensionImageLabels option is ignored

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-jenkins-shared-library#566]
**Describe the bug**
Labels which are specified via option `extensionImageLabels` do not appear in the build image as labels

**To Reproduce**
1. Add `extensionImageLabels` option to `odsComponentStageBuildOpenShiftImage` stage:

```groovy
// Jenkinsfile
odsComponentStageBuildOpenShiftImage(context, [
  extensionImageLabels: ["extensionImageLabelA": "Hello Ext A"],
  imageLabels: ["imageLabelA": "Hello A", "imageLabelB": "Hello B"],
])
```
2. Run Pipeline
3. Go to openshift namespace -> Image Streams -> <ImageName> -> :latest
4. `extensionImageLabels` are not present while `imageLabels` have been successfully added

**Expected behavior**
`extensionImageLabels` are added to the image as descripted in the documentation

Option | Description
-- | --
imageLabels | Pass labels which should be aded on the image. Each label will be prefixed with ext..
extensionImageLabels | Extra image labels added into imageLabels

Soruce: https://www.opendevstack.org/ods-documentation/opendevstack/3.x/jenkins-shared-library/component-pipeline.html#_odscomponentstagebuildopenshiftimage

**Screenshots**
![image](https://user-images.githubusercontent.com/17799657/105483510-3fd43680-5caa-11eb-9b4a-1ea2f2874dd8.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
N/A

**Additional context**
As far as I understand it, all values of `extensionImageLabels` are merged with those of `imageLabels`. If so, isn't `extensionImageLabels` obsolete and could be completely replaced by `imageLabels`?

**Comment by clemensutschig** [comment]
@SimonGolms  . they sit on the global context - and NOT on the stage
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/BuildOpenShiftImageStage.groovy#L48
