### ISSUE TITLE
provide stage to create /update environment based on data in oc*-config

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#59]
Based on an discussion we had @michaelsauter  - it'd be great if people can export /amend config in oc*config - and the shared lib picks it up with tailor to deploy / update / replace it. I think with all the granular magic of tailor this should now be easily possible ... (based on compare local, etc.)

**Comment by michaelsauter** [comment]
Yes, this should be possible with Tailor. Ideally the `ocp-config` is seeded from the quickstarter, and then the Jenkins pipeline can run Tailor. Also, not sure if Jenkins can do this, but maybe one could have a manual "deploy" step where users can inspect Tailor's plan and have to click to apply it (just a thought, I know that Gitlab can do this)

The first step (I think) would be to add Tailor to the base image, and then we can try it (e.g. in our initiative, we have an up-to-date `ocp-config` folder which we use to evolve our infrastructure).

**Comment by michaelsauter** [comment]
I'll close this in favour of #96, which described the proposal in more detail.
