### ISSUE TITLE
[bug]: component master pipeline runs again after succeeding release via release manager

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-jenkins-shared-library#593]
**Describe the bug**
If a release is performed via the release manager, the Jenkins job for `{component}-master` is triggered again after a successful process and merge into master commit.

**To Reproduce**
1. Trigger new release via Release Manager

**Expected behavior**
Skip Jenkins job

**Screenshots**
N/A

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.1/master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
N/A

**Comment by clemensutschig** [comment]
@metmajer  - how come you folks never saw this .. this is a huge regression ... @jafarre-viewnext

**Comment by braisvq1996** [comment]
This is only on Master ?
https://github.com/opendevstack/ods-jenkins-shared-library/blob/3.x/src/org/ods/services/GitService.groovy#L115

**Comment by SimonGolms** [comment]
After further investigation with @clemensutschig we found the bug. There is a second commit message without the `[ci skip]`:

![image](https://user-images.githubusercontent.com/17799657/109118984-5c014280-7744-11eb-8f8c-b69ababcd07a.png)

This is triggered here:

https://github.com/opendevstack/ods-jenkins-shared-library/blob/f2c13d599a27bad9fed701e5eddbe8d180a95fae/src/org/ods/orchestration/FinalizeStage.groovy#L189

and as you can see it's missing the `[ci skip]` pattern in L265:

https://github.com/opendevstack/ods-jenkins-shared-library/blob/f2c13d599a27bad9fed701e5eddbe8d180a95fae/src/org/ods/services/GitService.groovy#L263-L269

**Comment by metmajer** [comment]
@SimonGolms @clemensutschig thanks for the finding! @braisvq1996 do you want to make a contribution? The commit message in L265 needs to be augmented as described above by Simon.

**Comment by clemensutschig** [comment]
I would change the message btw .. to "ODS RM merge from ${branchToMerge}"

**Comment by metmajer** [comment]
@clemensutschig @SimonGolms I'll provide a quick PR

**Comment by metmajer** [comment]
@SimonGolms resolved. Would you please describe the scenario for an automated test case in an issue inside https://github.com/opendevstack/ods-e2e-tests that we'll can take care of later? Cheers!

**Comment by clemensutschig** [comment]
testcase should yield:

release manager: master (one component frontend) - version: "XXX", env: "DEV" -> mro pipeline master run
- component build (frontend-release-XXX) -> skip ci 
- component build (frontend-master) -> skip ci
