### ISSUE TITLE
SonarQube Scaner fails for SonarQube Enterprise Edition

### ISSUE THREAD

**Issue by jonathrodriguez** [opendevstack/ods-jenkins-shared-library#601]
**Describe the bug**
Having a feature branch (non long-lived), when a PR is open, the stage 'SonarQube Analysis' fails with an error indicating that for PRs the sonar.branch.name property should not be informed.

**To Reproduce**
1. Setup the environment variable SONARQUBE_EDITION with value 'enterprise' in Jenkins master node.
2. Leave sonar scanner properties as default.
3. Create a branch with some code in your project, push it and open a PR.
4. Go to your jenkins instance and follow the build until the error.

**Expected behavior**
The sonarqube analysis is performed and the pull request is decorated with sonarqube report.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack: 3.1
 - SonarQube Enterprise Edition - Version 8.2 (build 32929)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
ERROR: Error during SonarQube Scanner execution
ERROR: A pull request analysis cannot have the branch analysis parameter 'sonar.branch.name'
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

**Additional context**
Following the code of the shared library we found that:
In org.ods.component.ScanWithSonarStage.groovy@71 the property referenced in the error is always stablished.
and then with those properties the sonar service is called, resulting that:
In org.ods.services.SonarQubeService.groovy@28 the property is set as parameter for the scanner, no matter if the pullRequestInfo parameter is present or not.

**Comment by michaelsauter** [comment]
What SonarQube version is this?

**Comment by jonathrodriguez** [comment]
> What SonarQube version is this?

SonarQube Enterprise Edition - Version 8.2 (build 32929)

I will update the issue with that information.

**Comment by michaelsauter** [comment]
I was able to reproduce this against a Developer Version 8.4.1. Originally the feature was built against 7.9, so my assumption is that 8.0 introduced a breaking change that prevents both settings to be present. I can't find information on this right now, but I'll open a fix against `3.x` and `master`.
