### ISSUE TITLE
Transient error in MRO pipeline

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-jenkins-shared-library#609]
**Describe the bug**
The orchestration pipeline will fail when promoting a release from D to Q. After a few more retries (6 to be exact) it succeeds without any code or parameter changes.

Release Manager is configured to deploy 2 components, both of them `Typescript` quickstarters.

**To Reproduce**
1. Deploy a first release to D with the following params:
- environment: dev
- changeId: 0.0.4
- version: testok
2. Promote the release to Q with the following params:
- environment: qa
- changeId: 0.0.4
- version: testok
3. The Q release failed with the error defined in the log output further below.
4. After many retries, the release to Q ends up succeeding.

**Expected behavior**
I'd expect the first promotion from D to Q to work as expected without having to re-run multiple times until one of them succeeds.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 3.1

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
DEBUG: Current stage: 'Deploy' -> start agent stage: 'Init'
[Pipeline] }
+ cp -r /var/lib/jenkins/jobs/****-cd/jobs/****-cd-****-mro-pipeline-master/workspace/docs /tmp/workspace/****-cd/****-cd-****-mro-pipeline-master
cp: cannot stat '/var/lib/jenkins/jobs/****-cd/jobs/****-cd-****-mro-pipeline-master/workspace/docs': No such file or directory
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
WARN: script returned exit code 1
```

I guess the `/docs` folder the error is mentioning is the one belonging to the Release Manager repository which contains the document templates such as TIP.yaml and TIR.yaml. That folder has never been modified by the end-user.

/cc @metmajer

**Comment by clemensutschig** [comment]
that should be a super quick fix - just add `| true` ... a shame we missed that

**Comment by felipecruz91** [comment]
@clemensutschig Where exactly should we add that? At the end of the `cp -r` command?

**Comment by clemensutschig** [comment]
yes ... at the end - similar to what is done at https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/JenkinsService.groovy#L30

**Comment by metmajer** [comment]
@felipecruz91 do you want to take care of a fix for mainline once you verified the approach solves the issue with your customer?
