### ISSUE TITLE
Nexus PyPi upload

### ISSUE THREAD

**Issue by yeyeto2788** [opendevstack/ods-jenkins-shared-library#612]
**Is your feature request related to a problem? Please describe.**
I want to be able to upload Python libraries to Nexus PyPi repository which seems not be an option on [`odscomponentstageuploadtonexus`](https://www.opendevstack.org/ods-documentation/opendevstack/3.x/jenkins-shared-library/component-pipeline.html#_odscomponentstageuploadtonexus) which is also an option within on the SonarType components [API](https://help.sonatype.com/repomanager3/rest-and-integration-api/components-api#ComponentsAPI-PyPI)

**Describe the solution you'd like**
Add the logic on the library so by calling just the same function (`odsComponentStageUploadToNexus`) will push the Python library to the Nexus PyPi repository and remove the manual code duplication on the `jenkinsfile` for each project.

**Comment by clemensutschig** [comment]
yak - I forgot to add the logic for more ... :( want to submit a PR .. it's in fact pretty easy (either hardcode) 

```
        } else if (repositoryType == 'raw') {
            nexusParams << ['raw.asset1.filename': distFile]
            nexusParams << ['raw.directory': (config.targetDirectory ?: context.projectId)]
        }
``` 

the only thing needed is to add `pypi.asset`
