### ISSUE TITLE
NullPointerException if error occurs during prepare stage

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-jenkins-shared-library#68]
If an error occurs during the prepare stage, then the call to set the build status in BitBucket might throw a NPE. We should figure out if we are able to set the build status, and if not, we should not even attempt to set the status. This affects 1.0.x and master.

**Comment by clemensutschig** [comment]
We have to provide much better err messages ;-)
Eg branch2env missing

**Comment by michaelsauter** [comment]
@clemensutschig Oh the error message is actually there:
```
ERROR: Param 'branchToEnvironmentMapping' is required
```
It's just that the NullPointer is printed before that so one thinks that the pipeline is totally broken :)
