### ISSUE TITLE
Tailor detects drift in cluster IP addresses 

### ISSUE THREAD

**Issue by felipecruz91** [opendevstack/ods-jenkins-shared-library#683]
**Describe the bug**
The issue described [here](https://github.com/opendevstack/ods-core/pull/983) is happening when using Release Manager to promote two components from D to Q.

**To Reproduce**
1. Create a Golang, Python, and Release Manager components through the Prov App.
2. Deploy them from Jira (using the Developer Preview button of EDP)
3. Deploy them from Jira to D.
4. Promote them from Jira to Q.
5. See error.

**Expected behavior**
Tailor to *not* detect a drift in the ClusterIP addresses.

**Screenshots**
![image](https://user-images.githubusercontent.com/15997951/123824506-66a03400-d8fe-11eb-9afe-6ea06adcf44a.png)

**Affected version (please complete the following information):**
 - OpenShift: 4.7
 - OpenDevStack (master branch, git commit 85f9a683a9e)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
~ svc/python-app to update
--- Current State (OpenShift cluster)
+++ Desired State (Processed template)
@@ -8,7 +8,7@@
   ​name: pytho-app
 ​spc:
   ​clusterIPs:
-  - 172.30.229.138
+  - 172.30.13163
   ​pors:
   ​- name: 8080-tc
     ​port: 8080

Summary: 0 in sync, 0 to create, 2 to update, 0 to delete

Updating dc/python-app ... --> oc apply -f - --namespace=edp5tb-test --selector=app=edp5tb-pythn-app
￼failed
Apply aborted: The Service "go-app" is invalid: 
* spec.clusterIPs[0]: Invalid value: []string{"172.30.65.190"}: may not change once set
* spec.clusterIPs: Invalid value: []string{"172.30.65.190"}: element [0] must match clusterIP
```

**Additional context**

cc/ @michaelsauter

**Comment by michaelsauter** [comment]
Add `preserve svc:/spec/clusterIPs` to the `Tailorfile`. We could add this by default to Tailor?

**Comment by felipecruz91** [comment]
It makes sense to have it by default in Tailor (otherwise we would need to add one Tailorfile per component when migrating ODS projects to OCP4). I'll open a PR with the change soon.

**Comment by felipecruz91** [comment]
FYI https://github.com/opendevstack/tailor/pull/242
