### ISSUE TITLE
If the deployment to P fails, the release is broken

### ISSUE THREAD

**Issue by jafarre-viewnext** [opendevstack/ods-jenkins-shared-library#708]
**Describe the bug**
If the release to P fails, you need to go deploy again into Q and the redeploy fails, because the corresponding tag already exists.

**To Reproduce**
1. move the release to P and make it fail
2. You have to go back to Q environment and the tag already exists and you cannot redeploy again.

**Expected behavior**
You can redeploy to Q and then retry the deploy to P.

**Screenshots**
![image-2021-07-09-11-28-20-685](https://user-images.githubusercontent.com/13270880/128519752-0d342308-d636-4cf5-bcb1-594c1ea313b4.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 1.1

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
Not available

**Additional context**

**Comment by jafarre-viewnext** [comment]
@clemensutschig , @michaelsauter , @metmajer , what do you think? Instead of failing, we could just auto-activate the rePromote build param when detecting this situation. But this could be done in all cases (allowing to freely redeploy into Q), or we may first find out whether a promotion to P just failed (trying to restrict redeploys to only the precise cases).

**Comment by clemensutschig** [comment]
that was by design ... and I don't want to open this .. when you fail on P - go fix in dev

**Comment by jafarre-viewnext** [comment]
@clemensutschig Well, I got this "issue" reported, because this implies creating a new project release just to retry the promotion to P. I am personally open to any decision that be taken.

**Comment by clemensutschig** [comment]
that's why we have that flag - if you add that to the bc / or as param - you can repromote .. (with caution) ...

**Comment by jafarre-viewnext** [comment]
@metmajer would it be fine if the build param was made available in Jenkins or we need some way to repromote from the Jira release manager issue?

**Comment by clemensutschig** [comment]
you need to add it (manuall) for this run to the buildconfig - that way it will bubble into jenkins - and you can repromote

**Comment by jafarre-viewnext** [comment]
I guess that's not something regular users can or know how to do, which I suppose is the intention.
For me it's fine, as long as everyone is fine with it.

**Comment by clemensutschig** [comment]
and regular users should not do it - that's why we have built it that way ..

**Comment by metmajer** [comment]
@clemensutschig I asked @jafarre-viewnext to file the issue. It's not clear when a re-promotion can be done or not. What's the reason/risk for not allowing an automated re-promotion of the tag from Q -> P if the release fails? A failure might be caused as well by an insufficient resource limits configuration or another transient error.

**Comment by metmajer** [comment]
@jafarre-viewnext @borja44 @clemensutschig I have captured the correct behavior including next steps internally.
