### ISSUE TITLE
getCommittedFiles fails when used under parallel statement

### ISSUE THREAD

**Issue by gerardcl** [opendevstack/ods-jenkins-shared-library#711]
**Describe the bug**
When using `getCommittedFiles` (https://github.com/opendevstack/ods-jenkins-shared-library/blob/da9e47f3afb679a9f367b431ba1d3c4642fe6d2f/src/org/ods/component/Context.groovy#L216) in a Jenkins parallel statement one might get a `java.io.NotSerializableException: org.jenkinsci.plugins.workflow.job.WorkflowRun` exception.

The issue is due to not treating it as a CPS (missing @nonCPS decorator). More info here -> https://www.jenkins.io/doc/book/pipeline/cps-method-mismatches/

**To Reproduce**
1. In a Jenkinsfile define a parallel statement and in the parallelized stages use the method `getCommittedFiles`.
2. Commit and push changes -> trigger jenkins build run
3. Pipeline will fail

**Expected behavior**
By using `getCommittedFiles` pipeline should never fail.

**Affected version (please complete the following information):**
 - OpenShift: all
 - OpenDevStack all

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
an exception which occurred:
	in field com.cloudbees.groovy.cps.impl.BlockScopeEnv.locals
	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@14e894a8
	in field com.cloudbees.groovy.cps.impl.CallEnv.caller
	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@47e1237d
	in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
	in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@3cf1eb9b
	in field com.cloudbees.groovy.cps.impl.CallEnv.caller
	in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@114d44dc
	in field com.cloudbees.groovy.cps.Continuable.e
	in object org.jenkinsci.plugins.workflow.cps.SandboxContinuable@4f36c60e
	in field org.jenkinsci.plugins.workflow.cps.CpsThread.program
	in object org.jenkinsci.plugins.workflow.cps.CpsThread@390a079f
	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.threads
	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@45eddeac
	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@45eddeac
Caused: java.io.NotSerializableException: org.jenkinsci.plugins.workflow.job.WorkflowRun
```

**Additional context**
Might require promoting to master, 4.x, ... and other releases?

FYI @michaelsauter  @metmajer @sino92

**Comment by michaelsauter** [comment]
Is `@nonCPS` actually correct there? The methods called run pipeline steps. Is this not an issue due to https://www.jenkins.io/doc/book/pipeline/cps-method-mismatches/#use-of-pipeline-steps-fromnoncps?

**Comment by gerardcl** [comment]
I believe the issue is due to the way the method is implemented and also to being part of the library which makes it be treated as CPS, so making it nonCPS fixes de issue.

So far, that is what has been ended up being detected when narrowing down our failing pipelines.

**Comment by gerardcl** [comment]
Indeed, although now the pipeline is working, I see now the following message:
`expected to call org.ods.component.Context.getCommittedFiles but wound up catching org.ods.component.Context.getLastSuccessfulCommit; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/`

So I am checking adding also the decorator to that `getLastSuccessfulCommit` library method.

**Comment by gerardcl** [comment]
ok, this is pretty weird, I will continue investigating, for now I will delete the PRs... we might just be misusing the library somewhere else... :(

**Comment by gerardcl** [comment]
ok, basically jenkins is having a weird behaviour and depending on the state of the pipeline it might decide the method is CSP treated or not...will continue trying to understand more the problem... so far -> closing this one for now!
