### ISSUE TITLE
java.util.ArrayList$Itr error when using the orchestration pipeline

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-jenkins-shared-library#745]
**Describe the bug**
We have a project that is using a huge amount of resources for theis Jenkins-master instance (20 GB and JVM is -Xms10g -Xmx18g) in order to aboid this error, but it still appear from time to time when running developer previews.
I have only seen this if **document generation is enabled**.

**To Reproduce**
1. Make use of the orchestration pipeline to deploy some components and enable document generation
2. Keep running developer previews without increasing Jenkins resources until you see this error

**Expected behavior**
The execution of the orchestration pipeline with document generation should not fail

**Screenshots**
Resources usage when error happened:
![captura](https://user-images.githubusercontent.com/26645694/138669469-d855228a-3209-4813-aef0-0a26f47e5b64.jpg)

Log where the error took place):
![captura2](https://user-images.githubusercontent.com/26645694/138670259-add16548-2596-4cd6-867c-4f366f507444.jpg)

Another log where the error happened:
![image](https://user-images.githubusercontent.com/26645694/138672119-3b89589a-8a53-4d92-be4f-3fa41a1a4af2.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11 and 4.7
 - OpenDevStack 3.x and 4.x

**Comment by clemensutschig** [comment]
@braisvq1996 - as discussed please test a couple of more runs of this combo - so we really see if there is not more to fix. 
also, I would add stories and tests etc ... so we get more traction now on the levadoc case - and see what we have missed there. 

@metmajer - fyi

**Comment by clemensutschig** [comment]
we are stuck with the component pipeline (we get the $Itr - seriously at the script.sh!) @michaelsauter any ideas?

**Comment by michaelsauter** [comment]
I looked at the source code right now but I do not understand how that line could produce an exception that `java.util.ArrayList$Itr` is not serialisable. Which list is used there? Are you sure the exception is from that line - and that there isn't an issue in reporting the exception?

**Comment by clemensutschig** [comment]
so - with a while & sleep it seems to work ... :(

Tmrw we'll stick even more stories++ into jira to see if there is more we missed ...

**Comment by braisvq1996** [comment]
with the changes on https://github.com/opendevstack/ods-jenkins-shared-library/pull/980 and https://github.com/opendevstack/ods-core/pull/1217 we do not have more memory issues with Jenkins so issue can be closed
