### ISSUE TITLE
Openshift pipelines always in pending status

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-jenkins-shared-library#747]
**Describe the bug**
When we make a commit with [ci skip] or similar to avoid building/deploying the component the pipeline created will always be in pending status.

**To Reproduce**
1. Make a commit with [ci skip]
2. Wait for the pipeline to finish in Jenkins
3. Check the status of the pipeline in Openshift

**Expected behavior**
The pipeline in Openshift should be in completed state

**Screenshots**
![image](https://user-images.githubusercontent.com/26645694/138712412-fc591a71-1b59-4c92-843f-29d4cff6d132.png)

**Affected version (please complete the following information):**
 - OpenShift: 3.11 and 4.7
 - OpenDevStack 3.x and 4.x

**Additional context**
This happens the most with orchestration pipeline as will always makes a commit into the component with [ci skip]

**Comment by braisvq1996** [comment]
In OCP4, and using ODS 4 I can see that the Release Manager Pipelines that were successfull are still in running state in OpenShift

**Comment by metmajer** [comment]
@braisvq1996 so donee have a problem?

**Comment by braisvq1996** [comment]
@metmajer this happens in ODS 3 and 4, but it should not be critical.
The pipelines in pending status does not make new pipelines able to run as this is the status in Openshift not in Jenkins

As soon as we have some time we will take a look at this
