### ISSUE TITLE
Method Conflict on repositoryType='pypi' ?

### ISSUE THREAD

**Issue by jchaves** [opendevstack/ods-jenkins-shared-library#785]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/0d7713e38e9b864d9f2cb638723fd0c57ca521a3/src/org/ods/services/NexusService.groovy#L100

Without knowing too much about the UniRest lib, it seems that the way we are constructing our rest call on the line above is causing some conflict that causes 'pypi' artifacts to end up stored in Nexus with the file name "application/octet-stream".

It would seem that there is a conflict with the method we are trying to call ( 1 ) and the one that is effectively called ( 2 )
[1]: https://github.com/Kong/unirest-java/blob/838cd1d6bb9c80d2e790d8d36fbcf511a248b016/unirest/src/main/java/kong/unirest/HttpRequestMultiPart.java#L69
[2] : https://github.com/Kong/unirest-java/blob/838cd1d6bb9c80d2e790d8d36fbcf511a248b016/unirest/src/main/java/kong/unirest/HttpRequestMultiPart.java#L94

I'm no expert and am in fact having some difficulties following the flow in NexusService, but I guess the fact that we never define a filename in 'nexusParams' for the 'pypi' repositoryType might have something to do with this?

Maybe for type pypi we should use the more explicit [3]: https://github.com/Kong/unirest-java/blob/838cd1d6bb9c80d2e790d8d36fbcf511a248b016/unirest/src/main/java/kong/unirest/HttpRequestMultiPart.java#L87
?

Any feedback will be appreciated!

**Comment by clemensutschig** [comment]
I am lost - we do this according to the nexus doc - I am confused what's wrong if anything?

**Comment by jchaves** [comment]
Hi again,

yeah, I could definitely have been a bit clearer :) . The situation is that some users are reporting that their python artifacts are being stored in Nexus with the _literal_ filename "application/octet-stream".

I've just found the [nexus docs](https://help.sonatype.com/repomanager3/rest-and-integration-api/components-api?_ga=2.77467549.908396943.1637595218-1101382681.1637595218#ComponentsAPI-PyPI), and it seems pretty straightforward, and it would seems that we are doing it correctly.

However, we are calling a [method ](https://github.com/Kong/unirest-java/blob/838cd1d6bb9c80d2e790d8d36fbcf511a248b016/unirest/src/main/java/kong/unirest/HttpRequestMultiPart.java#L94) with parameters of types String , InputStream and String. (I guess the correct type parameters would have been, for our use case, String , InputStream and [ContentType ](https://github.com/Kong/unirest-java/blob/838cd1d6bb9c80d2e790d8d36fbcf511a248b016/unirest/src/main/java/kong/unirest/ContentType.java#L33)

My guess is that, based on that signature, the Unirest lib is preparing a request with 'application/octet-stream' as file name.

Were there some tests made when adding this functionality? I may try making some changes to [storeComplextArtifact](https://github.com/opendevstack/ods-jenkins-shared-library/blob/0d7713e38e9b864d9f2cb638723fd0c57ca521a3/src/org/ods/services/NexusService.groovy#L91) and doing some tests to see if I can get the desired results.

Meanwhile, as I said, I'm no expert on any of this, so if someone sees that I made any mistake with my assumptions, or something, please comment! :D

**Comment by jchaves** [comment]
For clarity, I'll make this edit in a separate comment: The actual file name on the nexus instance is 'octet-stream' , not 'application/octet-stream'.

I'm trying to figure out where does it get split. Or maybe, where does it come from. Not sure if nexus splits it on that end, or if it's coming from a different place and all my assumptions are wrong, or what might be happening, really. I'll keep updating after I am able to do some testing.

**Comment by clemensutschig** [comment]
we are testing this in an automated test (https://github.com/opendevstack/ods-jenkins-shared-library/blob/0d7713e38e9b864d9f2cb638723fd0c57ca521a3/test/groovy/org/ods/services/NexusServiceSpec.groovy#L122)

but it's really interesting - because we are not doing anything special for the `pypi` case?! . hmmmm
https://github.com/opendevstack/ods-jenkins-shared-library/blob/4.x/src/org/ods/component/UploadToNexusStage.groovy

I assume this is 3.x? - what's sort of scary is that the pypi flag is only on 3.x and not on master/4.x?!

**Comment by clemensutschig** [comment]
ps - this is the merge that only happened in 3.x 
https://github.com/opendevstack/ods-jenkins-shared-library/pull/615/files :(

**Comment by jchaves** [comment]
Sure.
Acording to user, this is the fragment:

```
stageBuild(context)
odsComponentStageUploadToNexus(
  context,
  [
    distributionFile: 'dist/filename-with-version-numbers-and-stuff.whl',
    repository: 'pypi-reponame',
    repositoryType: 'pypi'
  ]
)
```
I hope I'll be able to perform some testing during this afternoon, but can't really be sure yet :( . I'll keep updating you

**Comment by clemensutschig** [comment]
is this 3.x? or an early master fork? - and can you past the log from the jenkins run (without an internal server names, etc)

**Comment by jchaves** [comment]
We finally were ale to get some testing done, let me try to recap here the results:

- With a 'clean' 3.x lib, we get the filename 'octet-stream' in the nexus repo
- With [this change](https://github.com/jchaves/ods-jenkins-shared-library/commit/9e7db3ee4a3ebf868b6d1fab0ec1364c7e32bada) we somehow end up with a .zip file (I guess nexus renames it to conform to some standard?)
- With [this other change](https://github.com/jchaves/ods-jenkins-shared-library/commit/d1a85836aded9399cf8534c47ac513f0fe4aaefe), .zip again (if I recall correctly)
- With a 'clean' 4.x, 'octet-stream' again

While we were at it, the user showed me a succesful upload using postman, when we tried generating code for the 'Unirest' library, we saw that the following code would work:

```
HttpResponse<String> response = Unirest.post("[domain].com/service/rest/v1/components?repository=pypi-[repo]")

  .header("Authorization", "Basic [AUTH data]")

  .header("Cookie", "[COOKIE DATA]")

  .field("file", new File("[PATH TO FILE]/[FILENAME WITH VERSION AS SEEN ON JENKINSFILE].whl"))

  .asString();
```

The interesting line would be:

  **.field("file", new File("[PATH TO FILE]/[FILENAME WITH VERSION AS SEEN ON JENKINSFILE].whl"))**

so, maybe the easiest path to fixing this would be to stop handling pypi repos as a special case and go back to 'raw' file upload?

I'll try to get some more testing done, to see if I can provide a clean working patch.

Meanwhile, as always, any feedback is welcome :)

**Comment by metmajer** [comment]
@jchaves can we close this issue?

**Comment by jchaves** [comment]
Hi @metmajer,
To be completely honest, I had made a mental note to check on all of this before the holidays break, got busy with other stuff, and then I completely forgot.

There was some conflict waiting for the merge into 4.x [1], I just resolved it and, pending a review from Clemens, it should be ready to merge. Once we do that, everything should be ready to close this issue for good :)

[1] https://github.com/opendevstack/ods-jenkins-shared-library/pull/812/

I'll check later today and close it if everything looks fine

**Comment by jchaves** [comment]
@metmajer @clemensutschig 
we still have this PR open, and I don't think I have the permissions to merge and close it:
https://github.com/opendevstack/ods-jenkins-shared-library/pull/812
If you guys wanna take a look and accept it, we could close both the PR and this issue. Having it open is only creating noise at this point, in my opinion.

Thanks, and regards!
