### ISSUE TITLE
[bug]: rerunning of master pipeline after dev release via release-manager

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-jenkins-shared-library#793]
**Describe the bug**
After a release with the release manager to the dev environment, the generated release branch is merged back into the master branch and pushed. This push activates the Bitbucket webhook and triggers the Jenkins master pipeline again for a rerun. 

**To Reproduce**
1. Go To your release-manager pipeline and start a new build with parameter `environment: dev` 
2. After finishing the release, look to your master pipeline and see it running again.

**Expected behavior**
No unnecessary re-running of the master pipeline

**Screenshots**
N/A

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack >=3

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
N/A

**Additional context**
The keyword `[ci skip]` is in one of the commits, but the check of whether the pipeline should be started or skipped only considers the title of the merges commit (`Merge branch release/20211207.003` vs `Pull Request 672: docs update readme [ci skip]`) in which the keyword is missing.

![image](https://user-images.githubusercontent.com/17799657/145175799-debe7eac-f923-4998-84b0-f3407fd5658b.png)

**Comment by SimonGolms** [comment]
@metmajer & @clemensutschig

**Comment by clemensutschig** [comment]
@michaelsauter  @serverhorror  - can you take a look this must be in the CI skip routine :(

https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/GitService.groovy#L140

or @SimonGolms  - create a PR :)

**Comment by SimonGolms** [comment]
`isCiSkipInCommitMessage` should not be edited, because `[ci skip]` should only be respected in the subject of the commit message! Otherwise there will be problems if Bitbucket automatically summarizes the previous commit messages during a PR and a `[ci skip]` appears there!

Unfortunately, it's not obvious to me what the preferred merge strategy is and if it causes any other side effects, so I'd rather leave it to the experts ;)

**Comment by clemensutschig** [comment]
Ok we'll fix it on master and 4.x with a merge commit with a message that contains [ci skip].

You are on 4.x right?

**Comment by SimonGolms** [comment]
Not yet, this also still affects 3.x. I don't know if this was the case in the past as well, since we hadn't done any releases in the last 3 months.

**Comment by clemensutschig** [comment]
@SimonGolms can you past the log of the commit in the release manager where the merge back happens?

**Comment by clemensutschig** [comment]
@SimonGolms - assuming you tal about the re-integration to master .. here is the PR at work :)

![image](https://user-images.githubusercontent.com/40628552/148083178-795081f1-a4d1-4932-8235-ede3305d513d.png)

**Comment by clemensutschig** [comment]
@SimonGolms is this a must fix for 3.x?

**Comment by SimonGolms** [comment]
In regard to the triggering of unwanted side effects (murphy's law) and the unnecessary resource consumption and blocking of the system I would see it as such.
