### ISSUE TITLE
CI BROKEN: Tests are failing since a few merges

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-jenkins-shared-library#806]
**Describe the bug**
After merging #797 I was surprisingly confronted with a failed github action workflow run. Looking back in the commit list, that has happened now for several previous commits and was also already briefly discussed in #801. 

After looking into it with @michaelsauter, our current assumption is that something might have changed in the ubuntu-latest image that the gh action uses, probably something regarding user write permissions. Looking at our code, the spot were it fails is here: https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/ScanWithSonarStage.groovy#L271:
```
        File file = File.createTempFile("temp", ".md")
```
@hrcornejo do you remember why you picked `File.createTempFile()` over `step.writeFile()` here? Our guess is that it might work again with step.writeFile(). Could you try it out in case it does still work for your intended use?

We also saw that meanwhile a few CodeNarc issues were introduced in the commits that happened since the first failed merge. They need to be resolved in order to get the tests green again.

**Comment by clemensutschig** [comment]
this is mega weird ... seriously ... if I run the tests locally - they work ... I tried with openjdk 11 in my PR - that made the problem not go away :(

**Comment by renedupont** [comment]
[looks green by now](https://github.com/opendevstack/ods-jenkins-shared-library/commits/master) ... closing this issue.
