### ISSUE TITLE
Shared lib should support more than * and a full branch name for sonarqubeBranch

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-jenkins-shared-library#81]

**Comment by clemensutschig** [comment]
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/vars/stageScanForSonarqube.groovy#L3

**Comment by michaelsauter** [comment]
I think we could, for consistency, also support the "prefix matching", so if the value ends in `/`, then all branches starting with the prefix match.

However, keep in mind that setting this to something that applies to more than one branch is not very helpful has the sonarqube status is all over the place then ...

**Comment by clemensutschig** [comment]
@michaelsauter  - 1.1?

**Comment by michaelsauter** [comment]
I'd rather push it back to 1.2 - if users want multi-branch, they probably also want the paid version of SonarQube. Let's see how that integration looks liek first, and then roll out the changes required for it in 1.2.

**Comment by michaelsauter** [comment]
We will incorporate this into #174.
