### ISSUE TITLE
RM: *found unexecuted Jira tests* error during promote2Production when functional test only runs on D and QA

### ISSUE THREAD

**Issue by albertpuente** [opendevstack/ods-jenkins-shared-library#831]
**Describe the bug**
When acceptance/integration tests are only run on D and QA, and not in PROD, the orchestration pipeline will fail due to missing unexecuted tests that are defined in Jira for that version.

**To Reproduce**
Have a functional test in a test component that is only run for DEV/QA and the acceptance test modeled in Jira.

**Expected behavior**
The orchestration pipeline should not fail due to missing unexecuted ACCEPTANCE or INTEGRATION tests on P.

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: n/a
 - OpenDevStack: 3.x, 4.x and master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
java.lang.IllegalStateException: Error: found unexecuted Jira tests.
	at org.ods.orchestration.FinalizeStage.run(FinalizeStage.groovy:123)
	at org.ods.orchestration.Stage.execute(Stage.groovy:40)
	at ___cps.transform___(Native Method)
....
Finished: FAILURE
```

The context:
`FinalizeStage` - checks for unexecuted tests (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/FinalizeStage.groovy#L100) that are set thru (https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/orchestration/usecase/JiraUseCase.groovy#L319-L322)

Here we need the fix - the proposal is to check in the JiraUsecase:320 if the missing tests are of type `acceptance` or `integration` (via `project.getAutomatedTestsTypeAcceptance/Integration`) and if the targetEnvironment is `production` - and  then do NOT warn and fail!

**Comment by metmajer** [comment]
@albertpuente please give this some more thought. This error occurs when test cases in Jira are not executed. Example: test not implemented. This has got nothing to do with tests executed in D/Q but not in P. Test cases in Jira are considered mandatory.

**Comment by metmajer** [comment]
@albertpuente will you bring the results of our discussion to @s2oBCN tomorrow? He may be able to find a quick resolution.

**Comment by clemensutschig** [comment]
I think the fix is super surgical and we have all the methods in place ;-)
