### ISSUE TITLE
' in commit message breaks Build Openshift Image step

### ISSUE THREAD

**Issue by m-apsolon** [opendevstack/ods-jenkins-shared-library#86]
didn't try any other specials chars

**Comment by m-apsolon** [comment]
sorry, didn't see in time, exactly that what you got @ errors;

**Comment by michaelsauter** [comment]
Fix will be `value.replace("'","'\"'\"'")`, thanks @hugowschneider

**Comment by clemensutschig** [comment]
@m-apsolon  - do you contribute the fix? or work with @renedupont  - to make this happen?

**Comment by m-apsolon** [comment]
@clemensutschig no, haven't had time this week, can do next week

**Comment by renedupont** [comment]
@clemensutschig I'm planning on doing it tomorrow if time allows.

**Comment by michaelsauter** [comment]
FYI I played a little with this yesterday, and noticed that besides `'`, also `"` breaks the patching. Need to escape both. And the suggested solution above does not really work ;)

**Comment by clemensutschig** [comment]
@michaelsauter  - I suggest to remove the chars in the first place :) (and also a line feed and do a trim at the end)
