### ISSUE TITLE
Add Helm Support to Release Manager

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-jenkins-shared-library#866]
**Is your feature request related to a problem? Please describe.**

There are a quite a few cases where helm is needed/helpful to deploy and to be able to deploy via release manager

**Describe the solution you'd like**

The `ods-infra` type can already deploy helm charts. Right now this is deliberately prohibited:

* https://github.com/opendevstack/ods-jenkins-shared-library/blob/de3b3ebd7477ec1092fcd1bb23a861c960a206fc/src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy#L127-L130 

**Describe alternatives you've considered**

Nothing alternative considered

**Additional context**

This has been discussed in #554 already so this issue is to have a focused discussion about specifically helm and release manager.

1. I have a branch ready that allows helm charts to promote to `P` from `D` and can send it as a PR.
2. I haven't found a good place for the docs yet, any hint is appreciated

* https://github.com/serverhorror/ods-jenkins-shared-library/commit/06b18f721997dedd2898efa549c464cf7ae82359

**Comment by serverhorror** [comment]
This is also in relation to these: #537, #554

**Comment by serverhorror** [comment]
@s2oBCN -- ping! A little help how a good test would look like is much appreciated

**Comment by braisvq1996** [comment]
Closed by PR #916
