### ISSUE TITLE
Timeout in Openshift 4 due to autoscaler

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-jenkins-shared-library#903]
**Describe the bug**
When you deploy a container in ocp4 the current nodes may not be enough to do it and the cluster cutoscaler kicks in and scale up a new node. 
The problem is that the current timeout for the depoyment stage is set to 5 min and this is not enough to scale up a new node and deploy the container, resulting in a failure in the pipeline.

**To Reproduce**
1. Run component pipeline with deployment stage enabled
2. In the situation of not enough nodes, check Openshift events for the trigger of the nodes scale up.
4. See error in the pipeline

**Expected behavior**
The pipeline should end successfully

**Affected version:**
 - OpenShift: 4.9
 - OpenDevStack 4.x

**Comment by braisvq1996** [comment]
I have seen deployments that trigger the cluster to scale up and took arround 10 min for the deployment to be successfull.
I would increase the default to 15 to be on the safe side.

**Comment by michaelsauter** [comment]
@metmajer What would you expect to be done here? The cluster autoscaler is outside the ODS project, and if the scaling takes a very long time, then increasing the timeout as Brais suggested is the only option I believe? However I think waiting for ~10 minutes for your deployment to happen is not great, if this is a regular occurrence. Maybe the scaler should not kick in regularly?

**Comment by metmajer** [comment]
@michaelsauter the idea was to get your team's feedback and ensure we're not turning the wrong knobs.

**Comment by michaelsauter** [comment]
@metmajer Got it. As I said the suggestion makes sense for me.

**Comment by metmajer** [comment]
@braisvq1996 then please provide a PR. We want to push this change next week together with #899, #900.
