### ISSUE TITLE
odsComponentStageBuildOpenShiftImage API broken v3.x -> v4.x

### ISSUE THREAD

**Issue by segfault16** [opendevstack/ods-jenkins-shared-library#909]
**Describe the bug**
This change https://github.com/opendevstack/ods-jenkins-shared-library/commit/5512554d33c1b7139096a5a174e2e3003e3e7d91#diff-d8f79fbab3b26b1bf0c74c6c3009c1634bae992d20209ebd20fda6d53455513d removed the return value for odsComponentStageBuildOpenShiftImage stage.

**To Reproduce**

this code:
````
def res = odsComponentStageBuildOpenShiftImage(context, [resourceName: 'jenkins-tools', dockerDir: 'docker'])
echo "${res.image}"
````

produces `ARN: Error: java.lang.NullPointerException: Cannot get property 'image' on null object` on v4.x, works fine on v3.x

**Affected version (please complete the following information):**
 - OpenDevStack [v4.x]

**Comment by braisvq1996** [comment]
@segfault16 were you able to make use of the param context.shortGitCommit  ?
It is the default value used to tag the image 
![image](https://user-images.githubusercontent.com/26645694/170009822-47ebcbbd-926f-4d4e-9ea1-16bc21185928.png)

**Comment by segfault16** [comment]
Sure, but it's not the same as the image id with sha256 hash.

**Comment by segfault16** [comment]
@braisvq1996 @renedupont @michaelsauter 
Was this change in API by design or is it a mistake?

**Comment by michaelsauter** [comment]
@segfault16 I do not know, but just looking at the diff you linked I would think it was a mistake.

**Comment by renedupont** [comment]
@segfault16 I don't recall a specific reason why it shouldn't return anything. I guess looking at the code comment, it is important to keep the order though. Maybe just save the return val of stage.execute in a var and return it after the aqua run?

**Comment by braisvq1996** [comment]
Hi @segfault16 we have merge it into 4.x branch. Could you create a new PR for master branch ?
If not in the next version of ODS we will not have the change made in the PR for 4.x

**Comment by segfault16** [comment]
That's a rather strange way of maintaining branches I'd say... Why don't you merge 4.x -> master once there's been changes?

**Comment by braisvq1996** [comment]
Master branch will be the new 5.x branch when the new version is ready to be released so master does not contain the same commits/code as 4.x.

![image](https://user-images.githubusercontent.com/26645694/179545471-2847c764-fb94-4b13-aed6-51b17c140961.png)

**Comment by metmajer** [comment]
@braisvq1996 `master` is our integration branch and changes should be merged both into master and the current release branch always.
