### ISSUE TITLE
Expose the committed files with context object and script security

### ISSUE THREAD

**Issue by sino92** [opendevstack/ods-jenkins-shared-library#92]
We trigger a pipeline from inside the other in our monorepo app. It'd be convenient to check which files are committed before triggering the second pipeline in a stage.

**Comment by sino92** [comment]
Here're two possible implementations I've thought of in OdsContext.groovy: 
## SOLUTION I
 `  private String[] retrieveGitCommitFiles() {
    script.sh(
      returnStdout: true, script: "git diff-tree --no-commit-id --name-only -r ${config.gitCommit}"
    ).toString().split()
  }
`
This code lets the developer easily find the file(s) of their choice. However one downside is that it encourages the use of unpermitted static search methods such as `find` or `contains`...
<img width="962" alt="Screen Shot 2019-07-02 at 10 17 37" src="https://user-images.githubusercontent.com/16910110/60496264-c08ba600-9cb2-11e9-86cf-ef98906e15fb.png">
Clicking on the link would then bring: 
<img width="1052" alt="Screen Shot 2019-07-02 at 10 20 42" src="https://user-images.githubusercontent.com/16910110/60496460-22e4a680-9cb3-11e9-9245-ec81d9b48c67.png">
While some getter methods are harmless in themselves, they could potentially cause sniffing if combined with some others if permissions are granted. For example `method hudson.model.AbstractItem getParent` and a follow-up call of `method hudson.model.ItemGroup getItems` would let unpermitted users to get more information about the project. See ACL-aware method [https://plugins.jenkins.io/script-security](here)

## SOLUTION II
 The alternative method would look like: 
`  private String hasGitCommitFile(String filename) {
    script.sh(
      script: "git diff-tree --no-commit-id --name-only -r ${config.gitCommit}" | grep -i ${filename}", returnStatus: true
    ) == 0
  }
`
This is an out of the box solution as its contained in the shared library. The downside of this method is that it takes away the flexibility to evaluate the files available.

**Comment by michaelsauter** [comment]
Thanks for adding more context and possible solution. I took the freedom to edit your comment to use three backticks so that the code formats as a block.

Apart from the solution, I would like to raise that only inspecting the files modified in the current commit is likely not enough for your use case: Jenkins pipelines are only triggered on push, which means between the last pipeline run and this pipeline run, multiple commits might have been made, and you would need to inspect the files included in those commits as well, right?

**Comment by sino92** [comment]
Ah thanks for the backticks, its more readable now.
While one of the two solutions would be a good start it would certainly not cover the case of pushing multiple commits all at once. In order to achieve that, we'd need multiple commit hashes, very interesting point. We can raise another issue @michaelsauter for that as I believe we don't have a way to handle multiple commits at the moment?

**Comment by sino92** [comment]
`Jenkins pipelines are only triggered on push, which means between the last pipeline run and this pipeline run, multiple commits might have been made, and you would need to inspect the files included in those commits as well` @michaelsauter  To your point, I've found out we can retrieve those lost commits through **last successful Jenkins build and its corresponding commit**. 
Jenkins REST API exposes this information through `baseUrl/job/pipelineName/lastSuccessfulBuild`. When the git history is modified with a force push though, the hash of this build doesn't update - staying with a commit hash that no longer exist. In that case, we leave the lastSuccessful build empty. I wish we had a way of overwriting the `lastBuiltRevision` SHA there. 
What do you think? You can see the implementation details in add/context-doc branch.

**Comment by michaelsauter** [comment]
@sino92 Next GitHub trick :) You can use `>` in your message to quote someone else :)

I like the idea in general, looks much better now. Haven't thought much about it yet but I guess that could work. Probably needs some more error handling etc. but if you want to pursue it you could polish it up and add this kind of info to the ODS context. Ideally the information is only pulled on demand so that we do not slow down pipelines that do not need this kind of info.

**Comment by sino92** [comment]
Hah learning a new trick every day:)! Will put it in practice right away cause I liked this idea. 
> Ideally the information is only pulled on demand so that we do not slow down pipelines that do not need this kind of info.

Especially since I use curl. To tail it back to the original problem of seeing the files that are committed: `git rev-list lastSuccessfulCommit..currentCommit` would give us all the commits in between. Then the library or developer can use that to print out the files they're interested in for each commit: `git diff-tree --no-commit-id --name-only -r $commit`
