### ISSUE TITLE
Helm default flag --atomic leads to error when pulling latest

### ISSUE THREAD

**Issue by renedupont** [opendevstack/ods-jenkins-shared-library#922]
**Describe the bug**
We are using helm charts and in there, we configured to pull the latest image which we build earlier in the pipeline run:
```
image:
  ...
  tag: "latest"
```

As you can see [here](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy#L267), the latest tag gets set AFTER `helm upgrade `was done in the `rollout stage`. Before that, we only have commit hash tag that was created in the `image build stage`.
It is also important to know that we set [here](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy#L59) the helm default flags `--install` and `--atomic`, where atomic does the following:
```
--atomic       if set, upgrade process rolls back changes made in case of failed upgrade. The --wait flag will be set automatically if --atomic is used
--wait         if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as --timeout
```

**The following happened**: We did a pipeline run where we build successfully an image which was not able to run due to some misconfigurations. As a consequence, every pipeline run afterwards failed during helm upgrade due to `--atomic` not being successful and hence the latest tag was not set even though the image was successfully build. Since we are pulling `latest`, we never pulled the fixed image with the correct configuration but rather the one that failed in the past and we were basically stuck.

We "fixed" it by uninstalling the helm release in openshift and then provide via the rollout stage new helm default flags where we just pass `--install` without `--atomic`. 
```
...
  odsComponentStageRolloutOpenShiftDeployment(context,
    [helmDefaultFlags: ['--install']])
}
```
Also, we had to remove the `DeploymentConfig` that was created from the provisioning process and which we don't use since we use `Deployment `in our Helm chart.

Another "workaround" that we discussed was to not pull latest and provide the commit sha tag to helm (via helmValues in jenkinsfile rolloutstage) and just pull that.

@michaelsauter @kuebler

**Comment by clemensutschig** [comment]
see https://github.com/opendevstack/ods-jenkins-shared-library/pull/916/files 
we are currently revaming the whole thing - so if you want to try - enjoy :)

**Comment by clemensutschig** [comment]
@michaelsauter  - feel free to help... baking this was already kind of a hell of a ride :)

**Comment by metmajer** [comment]
@serverhorror did you test your PR against this behavior? Shall we close this one?

**Comment by renedupont** [comment]
Closing this as using git commit tag as image tag is by now the default way when using helm in ods.
See related issue #1027
