### ISSUE TITLE
Mail content when Jenkins build fails

### ISSUE THREAD

**Issue by mdurawa** [opendevstack/ods-jenkins-shared-library#93]
When a Jenkins build fails I get an error mail. But the place holder variables like ${script.DEFAULT_SUBJECT}, ${script.DEFAULT_CONTENT}, ... are not replaced by the actual content. 
So all mails have the content ${script.DEFAULT_CONTENT} without pointing to the real issue.

**Comment by clemensutschig** [comment]
@michaelsauter can you look into this?

**Comment by gerardcl** [comment]
hi @clemensutschig , we are already looking into this since we are now having a better chance for testing our selves :) 
I already spoke with @mdurawa and we will come back to him as soon as possible

**Comment by mdurawa** [comment]
is there any update on this?

**Comment by gerardcl** [comment]
we did not proceed yet
