### ISSUE TITLE
Allow duplicate tests on JiraUseCase

### ISSUE THREAD

**Issue by MinZe25** [opendevstack/ods-jenkins-shared-library#937]
**Is your feature request related to a problem? Please describe.**
It's not possible to have two tests related to a single jira usecase.

**Describe the solution you'd like**
Having an environment variable to control if it's active or not.

**Additional context**
The problem it's on the method: matchTestIssuesAgainstTestResults on JiraUseCase.

**Comment by metmajer** [comment]
@MinZe25 the ability to report back the test result to Jira requires a 1:1 relationship. I suggest you break down your test case into several ones if you require multiple implementations.
