### ISSUE TITLE
Risk Priority Number is rendered as N/A when is 0

### ISSUE THREAD

**Issue by albertpuente** [opendevstack/ods-jenkins-shared-library#955]
**Describe the bug**
The risk priority number in the documentation is rendered as "N/A" when its source value is 0, which is a valid value (and a number).

**To Reproduce**
1. Define a RA with RPN = 0.
2. Generate RA document.

**Expected behavior**
RPN should appear as 0.

**Affected version (please complete the following information):**
 - OpenDevStack 4.x

**Comment by metmajer** [comment]
Closed via #956
