### ISSUE TITLE
Deployment rollout stage issues

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/ods-jenkins-shared-library#957]
**Describe the bug**
odsComponentStageRolloutOpenShiftDeployment makes the DeploymentConfig pause/resume in the process to update the resource. 
If the resources have been paused before and it try to pause it again or if the resource is not paused and it tries to resume it again the pipeline will fail.
We have also seen that if the pipeline tries to rollout and the rollout is already running the pipeline will also fail.

**To Reproduce**
1. Run a component pipeline  with the one of the 3 situations mentioned before
2. See error

**Expected behavior**
Pipeline should be able to handle these errors and the pipeline should complete

**Screenshots**

_Rollout running and pipeline tries to trigger a rollout_
![image](https://user-images.githubusercontent.com/26645694/200520623-8611ca9d-c189-44c3-81ac-0427a06cce92.png)

_Deployment is not paused but pipeline tries to resume it_ 
![image](https://user-images.githubusercontent.com/26645694/200520788-217a2d3a-9e52-40e2-b938-3f9371e32624.png)

_Deployment is paused but pipeline tries to pause it_
![image](https://user-images.githubusercontent.com/26645694/200525549-e0ff32f5-89cd-4af2-8b82-70c0e24e834e.png)

**Affected version:**
 - OpenShift: 4.10
 - OpenDevStack 4.x

**Comment by metmajer** [comment]
@braisvq1996 can the support team please prepare a PR?
