### ISSUE TITLE
Replacement might fail if hostname is not 'bitbucket'

### ISSUE THREAD

**Issue by ungerts** [opendevstack/ods-jenkins-shared-library#98]
In OdsContext.groovy the string 'https://bitbucket' is replaced with 'https://cd_user@bitbucket'. The replacement will not work, if hostname is e.g. 'git'. Furthermore, we should discuss whether we need the replacement at all. In my opinion in Jenkins uernames are stored in credentials.

https://github.com/opendevstack/ods-jenkins-shared-library/blob/4f1a81a972a11d623279afc3d86e2fba4934f43a/src/org/ods/OdsContext.groovy#L341

**Comment by clemensutschig** [comment]
The replace we need.. to have git credentials Manager do its magic.. but we can go against http(s):// .. much cleaner

**Comment by clemensutschig** [comment]
@ungerts you fix this one as well? As Part of the mro work?

**Comment by ungerts** [comment]
@clemensutschig yes

**Comment by michaelsauter** [comment]
Fixed with ODS 2 and removal of global cd_user.
